# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

BROWSER_EXTENSION_PERMISSION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("isRequired", pa.bool_(), nullable=False),
        pa.field("risk", pa.string()),
    ]
)
