# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

IN_ORG_FILE_STATS_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("sha1", pa.string()),
        pa.field("orgPrevalence", pa.string()),
        pa.field("organizationPrevalence", pa.int32()),
        pa.field("orgFirstSeen", pa.timestamp("us", tz="UTC")),
        pa.field("orgLastSeen", pa.timestamp("us", tz="UTC")),
        pa.field("globalPrevalence", pa.string()),
        pa.field("globallyPrevalence", pa.int32()),
        pa.field("globalFirstObserved", pa.timestamp("us", tz="UTC")),
        pa.field("globalLastObserved", pa.timestamp("us", tz="UTC")),
        pa.field("topFileNames", pa.list_(pa.string())),
    ]
)
