# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

INVESTIGATION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("startTime", pa.timestamp("us", tz="UTC")),
        pa.field("endTime", pa.timestamp("us", tz="UTC")),
        pa.field("state", pa.string(), nullable=False),
        pa.field("cancelledBy", pa.string()),
        pa.field("statusDetails", pa.string()),
        pa.field("machineId", pa.string()),
        pa.field("computerDnsName", pa.string()),
        pa.field("triggeringAlertId", pa.string()),
    ]
)
