# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

FIRMWARE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("name", pa.string(), nullable=False),
        pa.field("type", pa.string()),
        pa.field("vendor", pa.string()),
        pa.field("family", pa.string()),
        pa.field("version", pa.string()),
        pa.field("additionalFields", pa.string()),
    ]
)
