# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

BASELINE_PROFILE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("name", pa.string()),
        pa.field("description", pa.string()),
        pa.field("benchmark", pa.string()),
        pa.field("version", pa.string()),
        pa.field("operatingSystem", pa.string()),
        pa.field("operatingSystemVersion", pa.string()),
        pa.field("status", pa.bool_(), nullable=False),
        pa.field("complianceLevel", pa.string()),
        pa.field("settingsNumber", pa.int32(), nullable=False),
        pa.field("createdBy", pa.string()),
        pa.field("lastUpdatedBy", pa.string()),
        pa.field("createdOnTimeOffset", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("lastUpdateTimeOffset", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("passedDevices", pa.int32(), nullable=False),
        pa.field("totalDevices", pa.int32(), nullable=False),
        pa.field("rbacGroupIdsProfileScope", pa.list_(pa.int32()), nullable=False),
        pa.field("rbacGroupNamesProfileScope", pa.list_(pa.string())),
        pa.field("deviceTagsProfileScope", pa.list_(pa.string())),
    ]
)
