# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

ASSET_BASELINE_ASSESSMENT_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string()),
        pa.field("configurationId", pa.string()),
        pa.field("deviceId", pa.string()),
        pa.field("deviceName", pa.string()),
        pa.field("profileId", pa.string()),
        pa.field("osPlatform", pa.string()),
        pa.field("osVersion", pa.string()),
        pa.field("rbacGroupId", pa.int64(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
        pa.field("isApplicable", pa.bool_(), nullable=False),
        pa.field("isCompliant", pa.bool_()),
        pa.field("dataCollectionTimeOffset", pa.string()),
        pa.field("complianceCalculationTimeOffset", pa.string()),
        pa.field("recommendedValue", pa.list_(pa.string())),
        pa.field("currentValue", pa.list_(pa.string())),
        pa.field("rawValue", pa.list_(pa.string())),
        pa.field("source", pa.list_(pa.string())),
        pa.field("isExempt", pa.bool_(), nullable=False),
        pa.field("complianceEvaluationDetails", pa.string()),
    ]
)
