# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
from __future__ import annotations

from mde_client.models.enums import (
    ALERT_CLASSIFICATION,
    ALERT_DETERMINATION,
    ALERT_SEVERITY,
    ALERT_STATUS,
    DEVICE_VALUE,
    EXCLUSION_REASON,
    ISOLATION_TYPE,
    KNOWN_REQUEST_SOURCE,
    SCAN_TYPE,
    TAG_ACTION,
)

from mde_client.endpoints.base import BasePayload


class AddDeviceGroupsPayload(BasePayload):
    deviceGroups: list[str]


class AddOrRemoveTagForMultipleMachinesPayload(BasePayload):
    Value: str
    Action: TAG_ACTION
    MachineIds: list[str]


class BatchDeleteDeviceAuthenticatedScanDefinitionPayload(BasePayload):
    ScanDefinitionIds: list[str]


class BatchDeleteIndicatorPayload(BasePayload):
    IndicatorIds: list[str]


class BatchUpdateAlertPayload(BasePayload):
    alertIds: list[str]
    status: ALERT_STATUS | None = None
    assignedTo: str | None = None
    classification: ALERT_CLASSIFICATION | None = None
    determination: ALERT_DETERMINATION | None = None
    comment: str | None = None


class BatchUpdateIndicatorPayload(BasePayload):
    Indicators: list[str]


class CancelPayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None


class CollectInvestigationPackagePayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None


class CreateAlertByReferencePayload(BasePayload):
    machineId: str
    severity: ALERT_SEVERITY
    title: str
    description: str
    recommendedAction: str
    eventTime: str
    reportId: str
    category: str | None = None


class DeleteDeviceGroupsPayload(BasePayload):
    ids: list[int]


class FindByIpPayload(BasePayload):
    ip: str
    timestamp: str


class GetLiveResponseResultDownloadLinkPayload(BasePayload):
    index: int


class GetScanHistoryByScanDefinitionIdPayload(BasePayload):
    ScanDefinitionIds: list[str]


class GetScanHistoryBySessionIdPayload(BasePayload):
    SessionIds: list[str]


class ImportPayload(BasePayload):
    Indicators: list[str]


class InitiateInvestigationPayload(BasePayload):
    Comment: str


class IsolatePayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None
    IsolationType: ISOLATION_TYPE | None = None


class LogsCollectionPayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None
    LogsCollectionParams: str | None = None


class OffBoardPayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None


class PostDeviceGroupsPayload(BasePayload):
    additionsCount: int
    deletionsCount: int
    deviceGroups: list[str]


class RestrictCodeExecutionPayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None


class RunAntiVirusScanPayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None
    ScanType: SCAN_TYPE


class RunCustomPlaybookPayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None
    Commands: list[str]


class RunLiveResponsePayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None
    Commands: list[str]


class SetDeviceValuePayload(BasePayload):
    DeviceValue: DEVICE_VALUE


class SetExclusionPayload(BasePayload):
    IsExcluded: bool
    ExclusionReason: EXCLUSION_REASON | None = None


class StartInvestigationPayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None


class StopAndQuarantineFilePayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None
    Sha1: str


class TagsPayload(BasePayload):
    Value: str
    Action: TAG_ACTION


class UnisolatePayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None


class UnrestrictCodeExecutionPayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None


__all__ = [
    "AddDeviceGroupsPayload",
    "AddOrRemoveTagForMultipleMachinesPayload",
    "BatchDeleteDeviceAuthenticatedScanDefinitionPayload",
    "BatchDeleteIndicatorPayload",
    "BatchUpdateAlertPayload",
    "BatchUpdateIndicatorPayload",
    "CancelPayload",
    "CollectInvestigationPackagePayload",
    "CreateAlertByReferencePayload",
    "DeleteDeviceGroupsPayload",
    "FindByIpPayload",
    "GetLiveResponseResultDownloadLinkPayload",
    "GetScanHistoryByScanDefinitionIdPayload",
    "GetScanHistoryBySessionIdPayload",
    "ImportPayload",
    "InitiateInvestigationPayload",
    "IsolatePayload",
    "LogsCollectionPayload",
    "OffBoardPayload",
    "PostDeviceGroupsPayload",
    "RestrictCodeExecutionPayload",
    "RunAntiVirusScanPayload",
    "RunCustomPlaybookPayload",
    "RunLiveResponsePayload",
    "SetDeviceValuePayload",
    "SetExclusionPayload",
    "StartInvestigationPayload",
    "StopAndQuarantineFilePayload",
    "TagsPayload",
    "UnisolatePayload",
    "UnrestrictCodeExecutionPayload",
]
