# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

SCANNED_TARGET_RESULT_CONTRACT_TYPE: pa.StructType = pa.struct(
    [
        pa.field("scanDuration", pa.time64("us"), nullable=False),
        pa.field("ip", pa.string()),
        pa.field("hostname", pa.string()),
        pa.field("scannedDeviceDescription", pa.string()),
        pa.field("errorMessage", pa.string()),
        pa.field("scanStatus", pa.string()),
    ]
)

AUTH_SCAN_HISTORY_CONTRACT_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("orgId", pa.string()),
        pa.field("scanDefinitionId", pa.string()),
        pa.field("sessionId", pa.string()),
        pa.field("scannerId", pa.string()),
        pa.field("numberOfSuccessfullyScannedTargets", pa.int32(), nullable=False),
        pa.field("numberOfTargets", pa.int32(), nullable=False),
        pa.field("scanStatus", pa.string()),
        pa.field("generalErrorMessage", pa.string()),
        pa.field("scannedTargets", pa.list_(SCANNED_TARGET_RESULT_CONTRACT_TYPE)),
    ]
)
