# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

PUBLIC_DISTRIBUTION_DTO_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("version", pa.string()),
        pa.field("installations", pa.int64(), nullable=False),
        pa.field("vulnerabilities", pa.int64(), nullable=False),
    ]
)
