# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

ASSET_CERTIFICATE_ASSESSMENT_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("deviceId", pa.string()),
        pa.field("deviceName", pa.string()),
        pa.field("thumbprint", pa.string()),
        pa.field("path", pa.string()),
        pa.field("signatureAlgorithm", pa.string()),
        pa.field("keySize", pa.int32(), nullable=False),
        pa.field("expirationDate", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("issueDate", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("subjectType", pa.string()),
        pa.field("serialNumber", pa.string()),
        pa.field("issuedTo", pa.string()),
        pa.field("issuedBy", pa.string()),
        pa.field("keyUsage", pa.string()),
        pa.field("extendedKeyUsage", pa.string()),
        pa.field("rbacGroupId", pa.int32(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
    ]
)
