# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

PUBLIC_PRODUCT_FIX_DTO_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string()),
        pa.field("name", pa.string()),
        pa.field("osBuild", pa.int64()),
        pa.field("productsNames", pa.list_(pa.string())),
        pa.field("url", pa.string()),
        pa.field("machineMissedOn", pa.int64(), nullable=False),
        pa.field("cveAddressed", pa.int64(), nullable=False),
    ]
)
