# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

CONFIGURATION_SCORE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("time", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("score", pa.float64(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
        pa.field("rbacGroupId", pa.int64()),
    ]
)
