# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

ASSET_SOFTWARE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("deviceId", pa.string()),
        pa.field("rbacGroupId", pa.int64(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
        pa.field("deviceName", pa.string()),
        pa.field("osPlatform", pa.string()),
        pa.field("softwareVendor", pa.string()),
        pa.field("softwareName", pa.string()),
        pa.field("softwareVersion", pa.string()),
        pa.field("numberOfWeaknesses", pa.int32(), nullable=False),
        pa.field("diskPaths", pa.list_(pa.string())),
        pa.field("registryPaths", pa.list_(pa.string())),
        pa.field("softwareFirstSeenTimestamp", pa.string()),
        pa.field("endOfSupportStatus", pa.string()),
        pa.field("endOfSupportDate", pa.string()),
        pa.field("softwareTags", pa.list_(pa.string())),
        pa.field("productCategory", pa.string()),
    ]
)
