# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

EXPORT_FILES_RESPONSE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("exportFiles", pa.list_(pa.string())),
        pa.field("generatedTime", pa.timestamp("us", tz="UTC")),
    ]
)
