# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

PUBLIC_ASSET_DTO_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string()),
        pa.field("computerDnsName", pa.string()),
        pa.field("osPlatform", pa.string()),
        pa.field("assetCriticalityLevel", pa.string()),
        pa.field("tags", pa.list_(pa.string())),
        pa.field("rbacGroupName", pa.string()),
        pa.field("rbacGroupId", pa.int64()),
    ]
)
