# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

ASSET_SOFTWARE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("deviceId", pa.string()),
        pa.field("rbacGroupId", pa.int64(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
        pa.field("deviceName", pa.string()),
        pa.field("osPlatform", pa.string()),
        pa.field("softwareVendor", pa.string()),
        pa.field("softwareName", pa.string()),
        pa.field("softwareVersion", pa.string()),
        pa.field("numberOfWeaknesses", pa.int32(), nullable=False),
        pa.field("diskPaths", pa.list_(pa.string())),
        pa.field("registryPaths", pa.list_(pa.string())),
        pa.field("softwareFirstSeenTimestamp", pa.string()),
        pa.field("endOfSupportStatus", pa.string()),
        pa.field("endOfSupportDate", pa.string()),
    ]
)
