# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

EVENT_HUB_PROPERTIES_TYPE: pa.StructType = pa.struct(
    [
        pa.field("eventHubResourceId", pa.string()),
        pa.field("subscriptionId", pa.string()),
        pa.field("resourceGroup", pa.string()),
        pa.field("namespace", pa.string()),
        pa.field("name", pa.string()),
    ]
)

STORAGE_ACCOUNT_PROPERTIES_TYPE: pa.StructType = pa.struct(
    [
        pa.field("storageAccountResourceId", pa.string()),
        pa.field("subscriptionId", pa.string()),
        pa.field("resourceGroup", pa.string()),
        pa.field("name", pa.string()),
    ]
)

WORKSPACE_PROPERTIES_TYPE: pa.StructType = pa.struct(
    [
        pa.field("workspaceResourceId", pa.string()),
        pa.field("subscriptionId", pa.string()),
        pa.field("resourceGroup", pa.string()),
        pa.field("name", pa.string()),
    ]
)

DATA_EXPORT_SETTINGS_LOG_DEFINITION_TYPE: pa.StructType = pa.struct(
    [
        pa.field("category", pa.string()),
        pa.field("enabled", pa.bool_(), nullable=False),
    ]
)

DATA_EXPORT_SETTINGS_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("designatedTenantId", pa.string()),
        pa.field("eventHubProperties", EVENT_HUB_PROPERTIES_TYPE),
        pa.field("storageAccountProperties", STORAGE_ACCOUNT_PROPERTIES_TYPE),
        pa.field("workspaceProperties", WORKSPACE_PROPERTIES_TYPE),
        pa.field("logs", pa.list_(DATA_EXPORT_SETTINGS_LOG_DEFINITION_TYPE)),
    ]
)
