# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

AUTH_PARAMS_BASE_TYPE: pa.StructType = pa.struct(
    [
        pa.field("keyVaultUri", pa.string()),
        pa.field("keyVaultSecretName", pa.string()),
        pa.field("type", pa.string()),
        pa.field("username", pa.string()),
        pa.field("password", pa.string()),
        pa.field("domain", pa.string()),
        pa.field("isgmsaUser", pa.bool_()),
        pa.field("packetPrivacy", pa.bool_()),
        pa.field("packetIntegrity", pa.bool_()),
        pa.field("privateKey", pa.string()),
        pa.field("communityString", pa.string()),
        pa.field("authProtocol", pa.string()),
        pa.field("authPassword", pa.string()),
        pa.field("privProtocol", pa.string()),
        pa.field("privPassword", pa.string()),
    ]
)

AGENT_CONTRACT_TYPE: pa.StructType = pa.struct(
    [
        pa.field("id", pa.string()),
        pa.field("machineId", pa.string()),
        pa.field("machineName", pa.string()),
        pa.field("lastSeen", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("assignedApplicationId", pa.string()),
        pa.field("scannerSoftwareVersion", pa.string()),
        pa.field(
            "lastCommandExecutionTimestamp",
            pa.timestamp("us", tz="UTC"),
            nullable=False,
        ),
        pa.field("mdeClientVersion", pa.string()),
    ]
)

SCAN_STATE_TYPE: pa.StructType = pa.struct(
    [
        pa.field("status", pa.string()),
        pa.field("failureReason", pa.string()),
        pa.field("executionDateTime", pa.timestamp("us", tz="UTC")),
    ]
)

ADVANCED_ACTIVE_CONFIGURATION_TYPE: pa.StructType = pa.struct(
    [
        pa.field("addresses", pa.list_(pa.string())),
        pa.field("siteId", pa.string()),
        pa.field("scanIdentifier", pa.string()),
        pa.field("maxConcurrentScans", pa.int32(), nullable=False),
        pa.field("portCheckTimeout", pa.float32(), nullable=False),
        pa.field("singleScanTimeout", pa.int32(), nullable=False),
        pa.field("disabledScanners", pa.list_(pa.string())),
        pa.field("enabledEndpoints", pa.list_(pa.string())),
        pa.field("exportHMI", pa.bool_(), nullable=False),
        pa.field("externalAddress", pa.bool_(), nullable=False),
        pa.field("enableTCPPortScan", pa.bool_(), nullable=False),
        pa.field("exportSuccessfullOnlyAddresses", pa.bool_(), nullable=False),
        pa.field("zone", pa.string()),
        pa.field("force", pa.bool_(), nullable=False),
        pa.field("safe", pa.bool_(), nullable=False),
    ]
)

DEVICE_AUTHENTICATED_SCAN_DEFINITION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("scanType", pa.string(), nullable=False),
        pa.field("scanName", pa.string()),
        pa.field("isActive", pa.bool_(), nullable=False),
        pa.field("scanAuthenticationParams", AUTH_PARAMS_BASE_TYPE),
        pa.field("target", pa.string()),
        pa.field("scannerAgent", AGENT_CONTRACT_TYPE),
        pa.field("orgId", pa.string()),
        pa.field("latestScan", SCAN_STATE_TYPE),
        pa.field("intervalInHours", pa.int32()),
        pa.field("createdBy", pa.string()),
        pa.field("targetType", pa.string()),
        pa.field("isTroubleshootMode", pa.bool_(), nullable=False),
        pa.field("advancedActiveConfiguration", ADVANCED_ACTIVE_CONFIGURATION_TYPE),
    ]
)
