# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

RELATED_FILE_INFO_TYPE: pa.StructType = pa.struct(
    [
        pa.field("fileIdentifier", pa.string()),
        pa.field("fileIdentifierType", pa.string()),
    ]
)

CUSTOM_PLAYBOOK_PARAMETER_TYPE: pa.StructType = pa.struct(
    [
        pa.field("key", pa.string(), nullable=False),
        pa.field("value", pa.string()),
    ]
)

CUSTOM_PLAYBOOK_COMMAND_TYPE: pa.StructType = pa.struct(
    [
        pa.field("type", pa.string(), nullable=False),
        pa.field("params", pa.list_(CUSTOM_PLAYBOOK_PARAMETER_TYPE)),
    ]
)

CUSTOM_PLAYBOOK_COMMAND_RESULT_TYPE: pa.StructType = pa.struct(
    [
        pa.field("index", pa.int32(), nullable=False),
        pa.field("command", CUSTOM_PLAYBOOK_COMMAND_TYPE),
        pa.field("startTime", pa.timestamp("us", tz="UTC")),
        pa.field("endTime", pa.timestamp("us", tz="UTC")),
        pa.field("commandStatus", pa.string(), nullable=False),
        pa.field("errors", pa.list_(pa.string())),
    ]
)

TROUBLESHOOT_INFO_TYPE: pa.StructType = pa.struct(
    [
        pa.field("expirationUtc", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("startTsModeUtc", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("paramsJsonFormatVersion", pa.int32(), nullable=False),
        pa.field("state", pa.int32(), nullable=False),
    ]
)

MACHINE_ACTION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("type", pa.string(), nullable=False),
        pa.field("title", pa.string()),
        pa.field("requestor", pa.string()),
        pa.field("requestorComment", pa.string()),
        pa.field("status", pa.string(), nullable=False),
        pa.field("machineId", pa.string()),
        pa.field("computerDnsName", pa.string()),
        pa.field("relatedFileInfo", RELATED_FILE_INFO_TYPE),
        pa.field("creationDateTimeUtc", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("lastUpdateDateTimeUtc", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("cancellationRequestor", pa.string()),
        pa.field("cancellationComment", pa.string()),
        pa.field("cancellationDateTimeUtc", pa.timestamp("us", tz="UTC")),
        pa.field("errorHResult", pa.int32(), nullable=False),
        pa.field("scope", pa.string()),
        pa.field("commands", pa.list_(CUSTOM_PLAYBOOK_COMMAND_RESULT_TYPE)),
        pa.field("troubleshootInfo", TROUBLESHOOT_INFO_TYPE),
        pa.field("externalId", pa.string()),
        pa.field("requestSource", pa.string(), nullable=False),
    ]
)
