# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

ACTION_AVAILABILITY_STATUS_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("action", pa.string(), nullable=False),
        pa.field("isAvailable", pa.bool_(), nullable=False),
        pa.field("notSupportedReason", pa.string()),
    ]
)
