# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

ASSET_HARDWARE_FIRMWARE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("deviceId", pa.string()),
        pa.field("rbacGroupId", pa.int64(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
        pa.field("deviceName", pa.string()),
        pa.field("componentType", pa.string()),
        pa.field("manufacturer", pa.string()),
        pa.field("componentName", pa.string()),
        pa.field("componentVersion", pa.string()),
        pa.field("additionalFields", pa.string()),
    ]
)
