# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

FILE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("sha1", pa.string(), nullable=False),
        pa.field("sha256", pa.string()),
        pa.field("md5", pa.string()),
        pa.field("globalPrevalence", pa.int64()),
        pa.field("globalFirstObserved", pa.timestamp("us", tz="UTC")),
        pa.field("globalLastObserved", pa.timestamp("us", tz="UTC")),
        pa.field("size", pa.int64()),
        pa.field("fileType", pa.string()),
        pa.field("isPeFile", pa.bool_()),
        pa.field("filePublisher", pa.string()),
        pa.field("fileProductName", pa.string()),
        pa.field("signer", pa.string()),
        pa.field("issuer", pa.string()),
        pa.field("signerHash", pa.string()),
        pa.field("isValidCertificate", pa.bool_()),
        pa.field("determinationType", pa.string(), nullable=False),
        pa.field("determinationValue", pa.string()),
    ]
)
