# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .alert import (
        ALERT_SCHEMA,
        ALERT_RELATED_USER_TYPE,
        LOGGED_ON_USER_TYPE,
        ALERT_COMMENT_TYPE,
        ALERT_EVIDENCE_TYPE,
        DOMAIN_TYPE,
    )
    from .baseline_configuration import BASELINE_CONFIGURATION_SCHEMA
    from .baseline_exception import (
        BASELINE_EXCEPTION_SCHEMA,
        BASELINE_CONFIGURATION_DTO_TYPE,
        BASELINE_EXCEPTION_DEVICE_DTO_TYPE,
        USER_DTO_TYPE,
    )
    from .baseline_profile import BASELINE_PROFILE_SCHEMA
    from .browser_extension_permission import BROWSER_EXTENSION_PERMISSION_SCHEMA
    from .browser_extensions import BROWSER_EXTENSIONS_SCHEMA
    from .configuration_score import CONFIGURATION_SCORE_SCHEMA
    from .data_export_settings import (
        DATA_EXPORT_SETTINGS_SCHEMA,
        EVENT_HUB_PROPERTIES_TYPE,
        STORAGE_ACCOUNT_PROPERTIES_TYPE,
        WORKSPACE_PROPERTIES_TYPE,
        DATA_EXPORT_SETTINGS_LOG_DEFINITION_TYPE,
    )
    from .device_authenticated_scan_agent import DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA
    from .device_authenticated_scan_definition import (
        DEVICE_AUTHENTICATED_SCAN_DEFINITION_SCHEMA,
        AGENT_CONTRACT_TYPE,
        SCAN_STATE_TYPE,
        ADVANCED_ACTIVE_CONFIGURATION_TYPE,
    )
    from .device_av_info import DEVICE_AV_INFO_SCHEMA
    from .device_group import (
        DEVICE_GROUP_SCHEMA,
        AAD_USERS_GROUP_TYPE,
        DEVICE_GROUP_PROPERTY_CONDITION_TYPE,
        DEVICE_GROUP_LIST_PROPERTY_CONDITION_TYPE,
        DEVICE_GROUP_RULES_TYPE,
    )
    from .domain import DOMAIN_SCHEMA
    from .file import FILE_SCHEMA
    from .firmware import FIRMWARE_SCHEMA
    from .incident import (
        INCIDENT_SCHEMA,
        VM_METADATA_TYPE,
        MTP_DEVICE_TYPE,
        MTP_ALERT_EVIDENCE_TYPE,
        MTP_ALERT_TYPE,
    )
    from .indicator import (
        INDICATOR_SCHEMA,
        CERTIFICATE_INDICATOR_INFORMATION_TYPE,
    )
    from .investigation import INVESTIGATION_SCHEMA
    from .ip import IP_SCHEMA
    from .library_files import LIBRARY_FILES_SCHEMA
    from .machine import (
        MACHINE_SCHEMA,
        MACHINE_IP_ADDRESS_TYPE,
    )
    from .machine_action import (
        MACHINE_ACTION_SCHEMA,
        RELATED_FILE_INFO_TYPE,
        CUSTOM_PLAYBOOK_PARAMETER_TYPE,
        CUSTOM_PLAYBOOK_COMMAND_TYPE,
        CUSTOM_PLAYBOOK_COMMAND_RESULT_TYPE,
        TROUBLESHOOT_INFO_TYPE,
    )
    from .public_product_dto import PUBLIC_PRODUCT_DTO_SCHEMA
    from .public_vulnerability_dto import PUBLIC_VULNERABILITY_DTO_SCHEMA
    from .recommendation import RECOMMENDATION_SCHEMA
    from .remediation_task import REMEDIATION_TASK_SCHEMA
    from .software import (
        SOFTWARE_SCHEMA,
        PUBLIC_DISTRIBUTION_DTO_TYPE,
    )
    from .user import USER_SCHEMA
    from .vulnerability import VULNERABILITY_SCHEMA

_NAME_TO_MODULE: dict[str, str] = {
    "ALERT_SCHEMA": "alert",
    "ALERT_RELATED_USER_TYPE": "alert",
    "LOGGED_ON_USER_TYPE": "alert",
    "ALERT_COMMENT_TYPE": "alert",
    "ALERT_EVIDENCE_TYPE": "alert",
    "DOMAIN_TYPE": "alert",
    "BASELINE_CONFIGURATION_SCHEMA": "baseline_configuration",
    "BASELINE_EXCEPTION_SCHEMA": "baseline_exception",
    "BASELINE_CONFIGURATION_DTO_TYPE": "baseline_exception",
    "BASELINE_EXCEPTION_DEVICE_DTO_TYPE": "baseline_exception",
    "USER_DTO_TYPE": "baseline_exception",
    "BASELINE_PROFILE_SCHEMA": "baseline_profile",
    "BROWSER_EXTENSION_PERMISSION_SCHEMA": "browser_extension_permission",
    "BROWSER_EXTENSIONS_SCHEMA": "browser_extensions",
    "CONFIGURATION_SCORE_SCHEMA": "configuration_score",
    "DATA_EXPORT_SETTINGS_SCHEMA": "data_export_settings",
    "EVENT_HUB_PROPERTIES_TYPE": "data_export_settings",
    "STORAGE_ACCOUNT_PROPERTIES_TYPE": "data_export_settings",
    "WORKSPACE_PROPERTIES_TYPE": "data_export_settings",
    "DATA_EXPORT_SETTINGS_LOG_DEFINITION_TYPE": "data_export_settings",
    "DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA": "device_authenticated_scan_agent",
    "DEVICE_AUTHENTICATED_SCAN_DEFINITION_SCHEMA": "device_authenticated_scan_definition",
    "AGENT_CONTRACT_TYPE": "device_authenticated_scan_definition",
    "SCAN_STATE_TYPE": "device_authenticated_scan_definition",
    "ADVANCED_ACTIVE_CONFIGURATION_TYPE": "device_authenticated_scan_definition",
    "DEVICE_AV_INFO_SCHEMA": "device_av_info",
    "DEVICE_GROUP_SCHEMA": "device_group",
    "AAD_USERS_GROUP_TYPE": "device_group",
    "DEVICE_GROUP_PROPERTY_CONDITION_TYPE": "device_group",
    "DEVICE_GROUP_LIST_PROPERTY_CONDITION_TYPE": "device_group",
    "DEVICE_GROUP_RULES_TYPE": "device_group",
    "DOMAIN_SCHEMA": "domain",
    "FILE_SCHEMA": "file",
    "FIRMWARE_SCHEMA": "firmware",
    "INCIDENT_SCHEMA": "incident",
    "VM_METADATA_TYPE": "incident",
    "MTP_DEVICE_TYPE": "incident",
    "MTP_ALERT_EVIDENCE_TYPE": "incident",
    "MTP_ALERT_TYPE": "incident",
    "INDICATOR_SCHEMA": "indicator",
    "CERTIFICATE_INDICATOR_INFORMATION_TYPE": "indicator",
    "INVESTIGATION_SCHEMA": "investigation",
    "IP_SCHEMA": "ip",
    "LIBRARY_FILES_SCHEMA": "library_files",
    "MACHINE_SCHEMA": "machine",
    "MACHINE_IP_ADDRESS_TYPE": "machine",
    "MACHINE_ACTION_SCHEMA": "machine_action",
    "RELATED_FILE_INFO_TYPE": "machine_action",
    "CUSTOM_PLAYBOOK_PARAMETER_TYPE": "machine_action",
    "CUSTOM_PLAYBOOK_COMMAND_TYPE": "machine_action",
    "CUSTOM_PLAYBOOK_COMMAND_RESULT_TYPE": "machine_action",
    "TROUBLESHOOT_INFO_TYPE": "machine_action",
    "PUBLIC_PRODUCT_DTO_SCHEMA": "public_product_dto",
    "PUBLIC_VULNERABILITY_DTO_SCHEMA": "public_vulnerability_dto",
    "RECOMMENDATION_SCHEMA": "recommendation",
    "REMEDIATION_TASK_SCHEMA": "remediation_task",
    "SOFTWARE_SCHEMA": "software",
    "PUBLIC_DISTRIBUTION_DTO_TYPE": "software",
    "USER_SCHEMA": "user",
    "VULNERABILITY_SCHEMA": "vulnerability",
}


def __getattr__(name: str) -> object:
    """Lazily import schema constants on first access (PEP 562).

    The resolved value is written back into the module's globals so
    subsequent accesses skip this function entirely.
    """
    module_name = _NAME_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value  # cache: subsequent access bypasses __getattr__
    return value


__all__ = [
    "AAD_USERS_GROUP_TYPE",
    "ADVANCED_ACTIVE_CONFIGURATION_TYPE",
    "AGENT_CONTRACT_TYPE",
    "ALERT_COMMENT_TYPE",
    "ALERT_EVIDENCE_TYPE",
    "ALERT_RELATED_USER_TYPE",
    "ALERT_SCHEMA",
    "BASELINE_CONFIGURATION_DTO_TYPE",
    "BASELINE_CONFIGURATION_SCHEMA",
    "BASELINE_EXCEPTION_DEVICE_DTO_TYPE",
    "BASELINE_EXCEPTION_SCHEMA",
    "BASELINE_PROFILE_SCHEMA",
    "BROWSER_EXTENSIONS_SCHEMA",
    "BROWSER_EXTENSION_PERMISSION_SCHEMA",
    "CERTIFICATE_INDICATOR_INFORMATION_TYPE",
    "CONFIGURATION_SCORE_SCHEMA",
    "CUSTOM_PLAYBOOK_COMMAND_RESULT_TYPE",
    "CUSTOM_PLAYBOOK_COMMAND_TYPE",
    "CUSTOM_PLAYBOOK_PARAMETER_TYPE",
    "DATA_EXPORT_SETTINGS_LOG_DEFINITION_TYPE",
    "DATA_EXPORT_SETTINGS_SCHEMA",
    "DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA",
    "DEVICE_AUTHENTICATED_SCAN_DEFINITION_SCHEMA",
    "DEVICE_AV_INFO_SCHEMA",
    "DEVICE_GROUP_LIST_PROPERTY_CONDITION_TYPE",
    "DEVICE_GROUP_PROPERTY_CONDITION_TYPE",
    "DEVICE_GROUP_RULES_TYPE",
    "DEVICE_GROUP_SCHEMA",
    "DOMAIN_SCHEMA",
    "DOMAIN_TYPE",
    "EVENT_HUB_PROPERTIES_TYPE",
    "FILE_SCHEMA",
    "FIRMWARE_SCHEMA",
    "INCIDENT_SCHEMA",
    "INDICATOR_SCHEMA",
    "INVESTIGATION_SCHEMA",
    "IP_SCHEMA",
    "LIBRARY_FILES_SCHEMA",
    "LOGGED_ON_USER_TYPE",
    "MACHINE_ACTION_SCHEMA",
    "MACHINE_IP_ADDRESS_TYPE",
    "MACHINE_SCHEMA",
    "MTP_ALERT_EVIDENCE_TYPE",
    "MTP_ALERT_TYPE",
    "MTP_DEVICE_TYPE",
    "PUBLIC_DISTRIBUTION_DTO_TYPE",
    "PUBLIC_PRODUCT_DTO_SCHEMA",
    "PUBLIC_VULNERABILITY_DTO_SCHEMA",
    "RECOMMENDATION_SCHEMA",
    "RELATED_FILE_INFO_TYPE",
    "REMEDIATION_TASK_SCHEMA",
    "SCAN_STATE_TYPE",
    "SOFTWARE_SCHEMA",
    "STORAGE_ACCOUNT_PROPERTIES_TYPE",
    "TROUBLESHOOT_INFO_TYPE",
    "USER_DTO_TYPE",
    "USER_SCHEMA",
    "VM_METADATA_TYPE",
    "VULNERABILITY_SCHEMA",
    "WORKSPACE_PROPERTIES_TYPE",
]
