# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

ACTION_AVAILABILITY_STATUS_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("action", pa.string(), nullable=False),
        pa.field("isAvailable", pa.bool_(), nullable=False),
        pa.field("notSupportedReason", pa.string()),
    ]
)
