# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

ALERT_RELATED_USER_TYPE: pa.StructType = pa.struct(
    [
        pa.field("userName", pa.string()),
        pa.field("domainName", pa.string()),
    ]
)

LOGGED_ON_USER_TYPE: pa.StructType = pa.struct(
    [
        pa.field("accountName", pa.string()),
        pa.field("domainName", pa.string()),
    ]
)

ALERT_COMMENT_TYPE: pa.StructType = pa.struct(
    [
        pa.field("comment", pa.string()),
        pa.field("createdBy", pa.string()),
        pa.field("createdTime", pa.timestamp("us", tz="UTC"), nullable=False),
    ]
)

ALERT_EVIDENCE_TYPE: pa.StructType = pa.struct(
    [
        pa.field("entityType", pa.string(), nullable=False),
        pa.field("evidenceCreationTime", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("sha1", pa.string()),
        pa.field("sha256", pa.string()),
        pa.field("fileName", pa.string()),
        pa.field("filePath", pa.string()),
        pa.field("processId", pa.int64()),
        pa.field("processCommandLine", pa.string()),
        pa.field("processCreationTime", pa.timestamp("us", tz="UTC")),
        pa.field("parentProcessId", pa.int64()),
        pa.field("parentProcessCreationTime", pa.timestamp("us", tz="UTC")),
        pa.field("parentProcessFileName", pa.string()),
        pa.field("parentProcessFilePath", pa.string()),
        pa.field("ipAddress", pa.string()),
        pa.field("url", pa.string()),
        pa.field("registryKey", pa.string()),
        pa.field("registryHive", pa.string()),
        pa.field("registryValueType", pa.string()),
        pa.field("registryValue", pa.string()),
        pa.field("registryValueName", pa.string()),
        pa.field("accountName", pa.string()),
        pa.field("domainName", pa.string()),
        pa.field("userSid", pa.string()),
        pa.field("aadUserId", pa.string()),
        pa.field("userPrincipalName", pa.string()),
        pa.field("detectionStatus", pa.string()),
    ]
)

DOMAIN_TYPE: pa.StructType = pa.struct(
    [
        pa.field("host", pa.string(), nullable=False),
    ]
)

ALERT_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("incidentId", pa.int64()),
        pa.field("investigationId", pa.int64()),
        pa.field("assignedTo", pa.string()),
        pa.field("severity", pa.string(), nullable=False),
        pa.field("status", pa.string(), nullable=False),
        pa.field("classification", pa.string()),
        pa.field("determination", pa.string()),
        pa.field("investigationState", pa.string()),
        pa.field("detectionSource", pa.string()),
        pa.field("detectorId", pa.string()),
        pa.field("category", pa.string()),
        pa.field("threatFamilyName", pa.string()),
        pa.field("title", pa.string()),
        pa.field("description", pa.string()),
        pa.field("alertCreationTime", pa.timestamp("us", tz="UTC")),
        pa.field("firstEventTime", pa.timestamp("us", tz="UTC")),
        pa.field("lastEventTime", pa.timestamp("us", tz="UTC")),
        pa.field("lastUpdateTime", pa.timestamp("us", tz="UTC")),
        pa.field("resolvedTime", pa.timestamp("us", tz="UTC")),
        pa.field("machineId", pa.string()),
        pa.field("computerDnsName", pa.string()),
        pa.field("rbacGroupName", pa.string()),
        pa.field("aadTenantId", pa.string()),
        pa.field("relatedUser", ALERT_RELATED_USER_TYPE),
        pa.field("threatName", pa.string()),
        pa.field("mitreTechniques", pa.list_(pa.string())),
        pa.field("loggedOnUsers", pa.list_(LOGGED_ON_USER_TYPE)),
        pa.field("comments", pa.list_(ALERT_COMMENT_TYPE)),
        pa.field("evidence", pa.list_(ALERT_EVIDENCE_TYPE)),
        pa.field("domains", pa.list_(DOMAIN_TYPE)),
    ]
)
