# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

ASSET_HARDWARE_FIRMWARE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("deviceId", pa.string()),
        pa.field("rbacGroupId", pa.int64(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
        pa.field("deviceName", pa.string()),
        pa.field("componentType", pa.string()),
        pa.field("manufacturer", pa.string()),
        pa.field("componentName", pa.string()),
        pa.field("componentVersion", pa.string()),
        pa.field("additionalFields", pa.string()),
    ]
)
