# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

ASSET_CONFIGURATION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("deviceId", pa.string()),
        pa.field("rbacGroupId", pa.int64(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
        pa.field("deviceName", pa.string()),
        pa.field("osPlatform", pa.string()),
        pa.field("osVersion", pa.string()),
        pa.field("timestamp", pa.string()),
        pa.field("configurationId", pa.string()),
        pa.field("configurationCategory", pa.string()),
        pa.field("configurationSubcategory", pa.string()),
        pa.field("configurationImpact", pa.float64(), nullable=False),
        pa.field("isCompliant", pa.bool_(), nullable=False),
        pa.field("isApplicable", pa.bool_(), nullable=False),
        pa.field("isExpectedUserImpact", pa.bool_(), nullable=False),
        pa.field("configurationName", pa.string()),
        pa.field("recommendationReference", pa.string()),
    ]
)
