# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

BASELINE_PROFILE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("name", pa.string()),
        pa.field("description", pa.string()),
        pa.field("benchmark", pa.string()),
        pa.field("version", pa.string()),
        pa.field("operatingSystem", pa.string()),
        pa.field("operatingSystemVersion", pa.string()),
        pa.field("status", pa.bool_(), nullable=False),
        pa.field("complianceLevel", pa.string()),
        pa.field("settingsNumber", pa.int32(), nullable=False),
        pa.field("createdBy", pa.string()),
        pa.field("lastUpdatedBy", pa.string()),
        pa.field("createdOnTimeOffset", pa.timestamp("ms"), nullable=False),
        pa.field("lastUpdateTimeOffset", pa.timestamp("ms"), nullable=False),
        pa.field("passedDevices", pa.int32(), nullable=False),
        pa.field("totalDevices", pa.int32(), nullable=False),
        pa.field("rbacGroupIdsProfileScope", pa.list_(pa.int32()), nullable=False),
        pa.field("rbacGroupNamesProfileScope", pa.list_(pa.string())),
        pa.field("deviceTagsProfileScope", pa.list_(pa.string())),
    ]
)
