# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

CONFIGURATION_SCORE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("time", pa.timestamp("ms"), nullable=False),
        pa.field("score", pa.float64(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
        pa.field("rbacGroupId", pa.int64()),
    ]
)
