# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

DEVICE_AV_INFO_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("machineId", pa.string()),
        pa.field("computerDnsName", pa.string()),
        pa.field("osKind", pa.string()),
        pa.field("osPlatform", pa.string()),
        pa.field("osVersion", pa.string()),
        pa.field("avMode", pa.string()),
        pa.field("avSignatureVersion", pa.string()),
        pa.field("avEngineVersion", pa.string()),
        pa.field("avPlatformVersion", pa.string()),
        pa.field("lastSeenTime", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("quickScanResult", pa.string()),
        pa.field("quickScanError", pa.string()),
        pa.field("quickScanTime", pa.timestamp("us", tz="UTC")),
        pa.field("fullScanResult", pa.string()),
        pa.field("fullScanError", pa.string()),
        pa.field("fullScanTime", pa.timestamp("us", tz="UTC")),
        pa.field("dataRefreshTimestamp", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("avEngineUpdateTime", pa.timestamp("us", tz="UTC")),
        pa.field("avSignatureUpdateTime", pa.timestamp("us", tz="UTC")),
        pa.field("avPlatformUpdateTime", pa.timestamp("us", tz="UTC")),
        pa.field("avIsSignatureUpToDate", pa.string()),
        pa.field("avIsEngineUpToDate", pa.string()),
        pa.field("avIsPlatformUpToDate", pa.string()),
        pa.field("avSignaturePublishTime", pa.timestamp("us", tz="UTC")),
        pa.field("avSignatureDataRefreshTime", pa.timestamp("us", tz="UTC")),
        pa.field("cloudProtectionState", pa.string()),
        pa.field("avModeDataRefreshTime", pa.timestamp("us", tz="UTC")),
        pa.field("rbacGroupName", pa.string()),
        pa.field("rbacGroupId", pa.int64()),
    ]
)
