# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

AAD_USERS_GROUP_TYPE: pa.StructType = pa.struct(
    [
        pa.field("displayName", pa.string()),
        pa.field("id", pa.string()),
    ]
)

DEVICE_GROUP_PROPERTY_CONDITION_TYPE: pa.StructType = pa.struct(
    [
        pa.field("condition", pa.string(), nullable=False),
        pa.field("value", pa.string()),
    ]
)

DEVICE_GROUP_LIST_PROPERTY_CONDITION_TYPE: pa.StructType = pa.struct(
    [
        pa.field("condition", pa.string(), nullable=False),
        pa.field("valuesList", pa.list_(pa.string())),
    ]
)

DEVICE_GROUP_RULES_TYPE: pa.StructType = pa.struct(
    [
        pa.field(
            "devicesNamesConditions", pa.list_(DEVICE_GROUP_PROPERTY_CONDITION_TYPE)
        ),
        pa.field(
            "devicesDomainsConditions", pa.list_(DEVICE_GROUP_PROPERTY_CONDITION_TYPE)
        ),
        pa.field(
            "devicesTagsConditions", pa.list_(DEVICE_GROUP_PROPERTY_CONDITION_TYPE)
        ),
        pa.field(
            "devicesOsConditions", pa.list_(DEVICE_GROUP_LIST_PROPERTY_CONDITION_TYPE)
        ),
    ]
)

DEVICE_GROUP_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.int32(), nullable=False),
        pa.field("priority", pa.int32(), nullable=False),
        pa.field("deviceGroupName", pa.string()),
        pa.field("isUnassignedDeviceGroup", pa.bool_(), nullable=False),
        pa.field("automationLevel", pa.string(), nullable=False),
        pa.field("description", pa.string()),
        pa.field("deviceCount", pa.int32(), nullable=False),
        pa.field("lastUpdateTime", pa.timestamp("us", tz="UTC")),
        pa.field("aadUsersGroups", pa.list_(AAD_USERS_GROUP_TYPE)),
        pa.field("deviceGroupRules", DEVICE_GROUP_RULES_TYPE),
    ]
)
