# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("machineId", pa.string()),
        pa.field("lastSeen", pa.timestamp("ms"), nullable=False),
        pa.field("computerDnsName", pa.string()),
        pa.field("assignedApplicationId", pa.string()),
        pa.field("scannerSoftwareVersion", pa.string()),
        pa.field("lastCommandExecutionTimestamp", pa.timestamp("ms"), nullable=False),
        pa.field("mdeClientVersion", pa.string()),
    ]
)
