# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

DLP_MACHINE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string()),
        pa.field("computerDnsName", pa.string()),
        pa.field("healthStatus", pa.string(), nullable=False),
        pa.field("configStatus", pa.string(), nullable=False),
        pa.field("lastSeen", pa.timestamp("us", tz="UTC")),
        pa.field("osPlatform", pa.string()),
        pa.field("version", pa.string()),
    ]
)
