# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

EXPORT_FILES_RESPONSE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("exportFiles", pa.list_(pa.string())),
        pa.field("generatedTime", pa.timestamp("us", tz="UTC")),
    ]
)
