# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

FILE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("sha1", pa.string(), nullable=False),
        pa.field("sha256", pa.string()),
        pa.field("md5", pa.string()),
        pa.field("globalPrevalence", pa.int64()),
        pa.field("globalFirstObserved", pa.timestamp("ms")),
        pa.field("globalLastObserved", pa.timestamp("ms")),
        pa.field("size", pa.int64()),
        pa.field("fileType", pa.string()),
        pa.field("isPeFile", pa.bool_()),
        pa.field("filePublisher", pa.string()),
        pa.field("fileProductName", pa.string()),
        pa.field("signer", pa.string()),
        pa.field("issuer", pa.string()),
        pa.field("signerHash", pa.string()),
        pa.field("isValidCertificate", pa.bool_()),
        pa.field("determinationType", pa.string(), nullable=False),
        pa.field("determinationValue", pa.string()),
    ]
)
