# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

FIRMWARE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("name", pa.string(), nullable=False),
        pa.field("type", pa.string()),
        pa.field("vendor", pa.string()),
        pa.field("family", pa.string()),
        pa.field("version", pa.string()),
        pa.field("additionalFields", pa.string()),
    ]
)
