# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

IN_ORG_IP_STATS_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("ipAddress", pa.string()),
        pa.field("orgPrevalence", pa.string()),
        pa.field("organizationPrevalence", pa.int32()),
        pa.field("orgFirstSeen", pa.timestamp("us", tz="UTC")),
        pa.field("orgLastSeen", pa.timestamp("us", tz="UTC")),
    ]
)
