# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

ALERT_COMMENT_TYPE: pa.StructType = pa.struct(
    [
        pa.field("comment", pa.string()),
        pa.field("createdBy", pa.string()),
        pa.field("createdTime", pa.timestamp("ms"), nullable=False),
    ]
)

VM_METADATA_TYPE: pa.StructType = pa.struct(
    [
        pa.field("vmId", pa.string()),
        pa.field("cloudProvider", pa.string(), nullable=False),
        pa.field("resourceId", pa.string()),
        pa.field("subscriptionId", pa.string()),
    ]
)

LOGGED_ON_USER_TYPE: pa.StructType = pa.struct(
    [
        pa.field("accountName", pa.string()),
        pa.field("domainName", pa.string()),
    ]
)

MTP_DEVICE_TYPE: pa.StructType = pa.struct(
    [
        pa.field("mdatpDeviceId", pa.string()),
        pa.field("aadDeviceId", pa.string()),
        pa.field("deviceDnsName", pa.string()),
        pa.field("osPlatform", pa.string()),
        pa.field("version", pa.string()),
        pa.field("osProcessor", pa.string()),
        pa.field("osBuild", pa.int64()),
        pa.field("healthStatus", pa.string()),
        pa.field("riskScore", pa.string()),
        pa.field("rbacGroupName", pa.string()),
        pa.field("firstSeen", pa.timestamp("ms")),
        pa.field("tags", pa.list_(pa.string())),
        pa.field("vmMetadata", VM_METADATA_TYPE),
        pa.field("onboardingStatus", pa.string()),
        pa.field("loggedOnUsers", pa.list_(LOGGED_ON_USER_TYPE)),
    ]
)

MTP_ALERT_EVIDENCE_TYPE: pa.StructType = pa.struct(
    [
        pa.field("entityType", pa.string(), nullable=False),
        pa.field("evidenceCreationTime", pa.timestamp("ms"), nullable=False),
        pa.field("verdict", pa.string(), nullable=False),
        pa.field("remediationStatus", pa.string(), nullable=False),
        pa.field("remediationStatusDetails", pa.string()),
        pa.field("sha1", pa.string()),
        pa.field("sha256", pa.string()),
        pa.field("fileName", pa.string()),
        pa.field("filePath", pa.string()),
        pa.field("processId", pa.int64()),
        pa.field("processCommandLine", pa.string()),
        pa.field("processCreationTime", pa.timestamp("ms")),
        pa.field("parentProcessId", pa.int64()),
        pa.field("parentProcessCreationTime", pa.timestamp("ms")),
        pa.field("parentProcessFileName", pa.string()),
        pa.field("parentProcessFilePath", pa.string()),
        pa.field("ipAddress", pa.string()),
        pa.field("url", pa.string()),
        pa.field("accountName", pa.string()),
        pa.field("domainName", pa.string()),
        pa.field("userSid", pa.string()),
        pa.field("aadUserId", pa.string()),
        pa.field("userPrincipalName", pa.string()),
        pa.field("mailboxDisplayName", pa.string()),
        pa.field("mailboxAddress", pa.string()),
        pa.field("clusterBy", pa.string()),
        pa.field("clusterByValue", pa.string()),
        pa.field("emailCount", pa.int64()),
        pa.field("sender", pa.string()),
        pa.field("recipient", pa.string()),
        pa.field("subject", pa.string()),
        pa.field("internetMessageId", pa.string()),
        pa.field("deliveryAction", pa.string()),
        pa.field("securityGroupId", pa.string()),
        pa.field("securityGroupName", pa.string()),
        pa.field("registryHive", pa.string()),
        pa.field("registryKey", pa.string()),
        pa.field("registryValueType", pa.string()),
        pa.field("registryValue", pa.string()),
        pa.field("detectionStatus", pa.string()),
        pa.field("deviceId", pa.string()),
        pa.field("applicationId", pa.string()),
        pa.field("applicationObjectId", pa.string()),
        pa.field("applicationName", pa.string()),
        pa.field("risk", pa.string()),
        pa.field("publisher", pa.string()),
    ]
)

MTP_ALERT_TYPE: pa.StructType = pa.struct(
    [
        pa.field("alertId", pa.string()),
        pa.field("providerAlertId", pa.string()),
        pa.field("incidentId", pa.int64(), nullable=False),
        pa.field("serviceSource", pa.string(), nullable=False),
        pa.field("creationTime", pa.timestamp("ms")),
        pa.field("lastUpdatedTime", pa.timestamp("ms")),
        pa.field("resolvedTime", pa.timestamp("ms")),
        pa.field("firstActivity", pa.timestamp("ms")),
        pa.field("lastActivity", pa.timestamp("ms")),
        pa.field("title", pa.string()),
        pa.field("description", pa.string()),
        pa.field("category", pa.string()),
        pa.field("status", pa.string(), nullable=False),
        pa.field("severity", pa.string(), nullable=False),
        pa.field("investigationId", pa.int64()),
        pa.field("investigationState", pa.string()),
        pa.field("classification", pa.string()),
        pa.field("determination", pa.string()),
        pa.field("detectionSource", pa.string()),
        pa.field("detectorId", pa.string()),
        pa.field("assignedTo", pa.string()),
        pa.field("actorName", pa.string()),
        pa.field("threatFamilyName", pa.string()),
        pa.field("mitreTechniques", pa.list_(pa.string())),
        pa.field("devices", pa.list_(MTP_DEVICE_TYPE)),
        pa.field("entities", pa.list_(MTP_ALERT_EVIDENCE_TYPE)),
    ]
)

INCIDENT_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("incidentId", pa.int64(), nullable=False),
        pa.field("incidentUri", pa.string()),
        pa.field("redirectIncidentId", pa.int64()),
        pa.field("incidentName", pa.string()),
        pa.field("createdTime", pa.timestamp("ms"), nullable=False),
        pa.field("lastUpdateTime", pa.timestamp("ms"), nullable=False),
        pa.field("assignedTo", pa.string()),
        pa.field("classification", pa.string(), nullable=False),
        pa.field("determination", pa.string(), nullable=False),
        pa.field("status", pa.string(), nullable=False),
        pa.field("severity", pa.string(), nullable=False),
        pa.field("tags", pa.list_(pa.string())),
        pa.field("comments", pa.list_(ALERT_COMMENT_TYPE)),
        pa.field("alerts", pa.list_(MTP_ALERT_TYPE)),
    ]
)
