# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

CERTIFICATE_INDICATOR_INFORMATION_TYPE: pa.StructType = pa.struct(
    [
        pa.field("issuer", pa.string()),
        pa.field("serial", pa.string()),
        pa.field("subject", pa.string()),
        pa.field("sha256", pa.string()),
    ]
)

INDICATOR_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("indicatorValue", pa.string()),
        pa.field("indicatorType", pa.string(), nullable=False),
        pa.field("action", pa.string(), nullable=False),
        pa.field("createdBy", pa.string()),
        pa.field("severity", pa.string(), nullable=False),
        pa.field("category", pa.int32()),
        pa.field("application", pa.string()),
        pa.field("educateUrl", pa.string()),
        pa.field("bypassDurationHours", pa.int32()),
        pa.field("title", pa.string()),
        pa.field("description", pa.string()),
        pa.field("recommendedActions", pa.string()),
        pa.field("creationTimeDateTimeUtc", pa.timestamp("ms"), nullable=False),
        pa.field("expirationTime", pa.timestamp("ms")),
        pa.field("lastUpdateTime", pa.timestamp("ms"), nullable=False),
        pa.field("lastUpdatedBy", pa.string()),
        pa.field("rbacGroupNames", pa.list_(pa.string())),
        pa.field("rbacGroupIds", pa.list_(pa.int32()), nullable=False),
        pa.field("certificateInfo", CERTIFICATE_INDICATOR_INFORMATION_TYPE),
        pa.field("notificationId", pa.uint8()),
        pa.field("notificationBody", pa.string()),
        pa.field("version", pa.string()),
        pa.field("mitreTechniques", pa.list_(pa.string())),
        pa.field("historicalDetection", pa.bool_(), nullable=False),
        pa.field("lookBackPeriod", pa.int32()),
        pa.field("generateAlert", pa.bool_(), nullable=False),
        pa.field("additionalInfo", pa.string()),
        pa.field("createdByDisplayName", pa.string()),
        pa.field("externalId", pa.string()),
        pa.field("createdBySource", pa.string(), nullable=False),
    ]
)
