# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

INVESTIGATION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("startTime", pa.timestamp("ms")),
        pa.field("endTime", pa.timestamp("ms")),
        pa.field("state", pa.string(), nullable=False),
        pa.field("cancelledBy", pa.string()),
        pa.field("statusDetails", pa.string()),
        pa.field("machineId", pa.string()),
        pa.field("computerDnsName", pa.string()),
        pa.field("triggeringAlertId", pa.string()),
    ]
)
