# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

LIBRARY_FILES_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("fileName", pa.string(), nullable=False),
        pa.field("sha256", pa.string()),
        pa.field("description", pa.string()),
        pa.field("creationTime", pa.timestamp("ms"), nullable=False),
        pa.field("lastUpdatedTime", pa.timestamp("ms"), nullable=False),
        pa.field("createdBy", pa.string()),
        pa.field("hasParameters", pa.bool_(), nullable=False),
        pa.field("parametersDescription", pa.string()),
    ]
)
