# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

PUBLIC_PRODUCT_FIX_DTO_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string()),
        pa.field("name", pa.string()),
        pa.field("osBuild", pa.int64()),
        pa.field("productsNames", pa.list_(pa.string())),
        pa.field("url", pa.string()),
        pa.field("machineMissedOn", pa.int64(), nullable=False),
        pa.field("cveAddressed", pa.int64(), nullable=False),
    ]
)
