# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

PUBLIC_ASSET_DTO_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string()),
        pa.field("computerDnsName", pa.string()),
        pa.field("osPlatform", pa.string()),
        pa.field("assetCriticalityLevel", pa.string()),
        pa.field("tags", pa.list_(pa.string())),
        pa.field("rbacGroupName", pa.string()),
        pa.field("rbacGroupId", pa.int64()),
    ]
)
