# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

__generated__ = True

if TYPE_CHECKING:
    from .action_availability_status.schema import ACTION_AVAILABILITY_STATUS_SCHEMA
    from .alert.schema import (
        ALERT_COMMENT_TYPE,
        ALERT_EVIDENCE_TYPE,
        ALERT_RELATED_USER_TYPE,
        ALERT_SCHEMA,
        DOMAIN_TYPE,
        LOGGED_ON_USER_TYPE,
    )
    from .asset_baseline_assessment.schema import ASSET_BASELINE_ASSESSMENT_SCHEMA
    from .asset_browser_extension.schema import ASSET_BROWSER_EXTENSION_SCHEMA
    from .asset_certificate_assessment.schema import ASSET_CERTIFICATE_ASSESSMENT_SCHEMA
    from .asset_configuration.schema import ASSET_CONFIGURATION_SCHEMA
    from .asset_hardware_firmware.schema import ASSET_HARDWARE_FIRMWARE_SCHEMA
    from .asset_non_cpe_software.schema import ASSET_NON_CPE_SOFTWARE_SCHEMA
    from .asset_software.schema import ASSET_SOFTWARE_SCHEMA
    from .asset_vulnerability.schema import ASSET_VULNERABILITY_SCHEMA
    from .auth_scan_history_contract.schema import (
        AUTH_SCAN_HISTORY_CONTRACT_SCHEMA,
        SCANNED_TARGET_RESULT_CONTRACT_TYPE,
    )
    from .baseline_configuration.schema import BASELINE_CONFIGURATION_SCHEMA
    from .baseline_exception.schema import (
        BASELINE_CONFIGURATION_DTO_TYPE,
        BASELINE_EXCEPTION_DEVICE_DTO_TYPE,
        BASELINE_EXCEPTION_SCHEMA,
        USER_DTO_TYPE,
    )
    from .baseline_profile.schema import BASELINE_PROFILE_SCHEMA
    from .browser_extension_permission.schema import BROWSER_EXTENSION_PERMISSION_SCHEMA
    from .browser_extensions.schema import BROWSER_EXTENSIONS_SCHEMA
    from .configuration_score.schema import CONFIGURATION_SCORE_SCHEMA
    from .data_export_settings.schema import (
        DATA_EXPORT_SETTINGS_LOG_DEFINITION_TYPE,
        DATA_EXPORT_SETTINGS_SCHEMA,
        EVENT_HUB_PROPERTIES_TYPE,
        STORAGE_ACCOUNT_PROPERTIES_TYPE,
        WORKSPACE_PROPERTIES_TYPE,
    )
    from .delta_asset_vulnerability.schema import DELTA_ASSET_VULNERABILITY_SCHEMA
    from .device_authenticated_scan_agent.schema import (
        DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA,
    )
    from .device_authenticated_scan_definition.schema import (
        ADVANCED_ACTIVE_CONFIGURATION_TYPE,
        AGENT_CONTRACT_TYPE,
        AUTH_PARAMS_BASE_TYPE,
        DEVICE_AUTHENTICATED_SCAN_DEFINITION_SCHEMA,
        SCAN_STATE_TYPE,
    )
    from .device_av_info.schema import DEVICE_AV_INFO_SCHEMA
    from .device_group.schema import (
        AAD_USERS_GROUP_TYPE,
        DEVICE_GROUP_LIST_PROPERTY_CONDITION_TYPE,
        DEVICE_GROUP_PROPERTY_CONDITION_TYPE,
        DEVICE_GROUP_RULES_TYPE,
        DEVICE_GROUP_SCHEMA,
    )
    from .dlp_machine.schema import DLP_MACHINE_SCHEMA
    from .domain.schema import DOMAIN_SCHEMA
    from .export_files_response.schema import EXPORT_FILES_RESPONSE_SCHEMA
    from .file.schema import FILE_SCHEMA
    from .firmware.schema import FIRMWARE_SCHEMA
    from .in_org_domain_stats.schema import IN_ORG_DOMAIN_STATS_SCHEMA
    from .in_org_file_stats.schema import IN_ORG_FILE_STATS_SCHEMA
    from .in_org_ip_stats.schema import IN_ORG_IP_STATS_SCHEMA
    from .incident.schema import (
        INCIDENT_SCHEMA,
        MTP_ALERT_EVIDENCE_TYPE,
        MTP_ALERT_TYPE,
        MTP_DEVICE_TYPE,
        VM_METADATA_TYPE,
    )
    from .indicator.schema import (
        CERTIFICATE_INDICATOR_INFORMATION_TYPE,
        INDICATOR_SCHEMA,
    )
    from .investigation.schema import INVESTIGATION_SCHEMA
    from .ip.schema import IP_SCHEMA
    from .library_files.schema import LIBRARY_FILES_SCHEMA
    from .list_1_of_import_indicator_result.schema import (
        LIST_1_OF_IMPORT_INDICATOR_RESULT_SCHEMA,
    )
    from .list_1_of_indicator.schema import LIST_1_OF_INDICATOR_SCHEMA
    from .machine.schema import (
        MACHINE_IP_ADDRESS_TYPE,
        MACHINE_SCHEMA,
    )
    from .machine_action.schema import (
        CUSTOM_PLAYBOOK_COMMAND_RESULT_TYPE,
        CUSTOM_PLAYBOOK_COMMAND_TYPE,
        CUSTOM_PLAYBOOK_PARAMETER_TYPE,
        MACHINE_ACTION_SCHEMA,
        RELATED_FILE_INFO_TYPE,
        TROUBLESHOOT_INFO_TYPE,
    )
    from .public_asset_dto.schema import PUBLIC_ASSET_DTO_SCHEMA
    from .public_asset_vulnerability_dto.schema import (
        PUBLIC_ASSET_VULNERABILITY_DTO_SCHEMA,
    )
    from .public_distribution_dto.schema import PUBLIC_DISTRIBUTION_DTO_SCHEMA
    from .public_product_dto.schema import PUBLIC_PRODUCT_DTO_SCHEMA
    from .public_product_fix_dto.schema import PUBLIC_PRODUCT_FIX_DTO_SCHEMA
    from .public_vulnerability_dto.schema import PUBLIC_VULNERABILITY_DTO_SCHEMA
    from .recommendation.schema import RECOMMENDATION_SCHEMA
    from .remediation_task.schema import REMEDIATION_TASK_SCHEMA
    from .software.schema import (
        PUBLIC_DISTRIBUTION_DTO_TYPE,
        SOFTWARE_SCHEMA,
    )
    from .user.schema import USER_SCHEMA
    from .vulnerability.schema import VULNERABILITY_SCHEMA


_NAME_TO_SLUG: dict[str, str] = {
    "ACTION_AVAILABILITY_STATUS_SCHEMA": "action_availability_status",
    "ALERT_SCHEMA": "alert",
    "ALERT_RELATED_USER_TYPE": "alert",
    "LOGGED_ON_USER_TYPE": "alert",
    "ALERT_COMMENT_TYPE": "alert",
    "ALERT_EVIDENCE_TYPE": "alert",
    "DOMAIN_TYPE": "alert",
    "ASSET_BASELINE_ASSESSMENT_SCHEMA": "asset_baseline_assessment",
    "ASSET_BROWSER_EXTENSION_SCHEMA": "asset_browser_extension",
    "ASSET_CERTIFICATE_ASSESSMENT_SCHEMA": "asset_certificate_assessment",
    "ASSET_CONFIGURATION_SCHEMA": "asset_configuration",
    "ASSET_HARDWARE_FIRMWARE_SCHEMA": "asset_hardware_firmware",
    "ASSET_NON_CPE_SOFTWARE_SCHEMA": "asset_non_cpe_software",
    "ASSET_SOFTWARE_SCHEMA": "asset_software",
    "ASSET_VULNERABILITY_SCHEMA": "asset_vulnerability",
    "AUTH_SCAN_HISTORY_CONTRACT_SCHEMA": "auth_scan_history_contract",
    "SCANNED_TARGET_RESULT_CONTRACT_TYPE": "auth_scan_history_contract",
    "BASELINE_CONFIGURATION_SCHEMA": "baseline_configuration",
    "BASELINE_EXCEPTION_SCHEMA": "baseline_exception",
    "BASELINE_CONFIGURATION_DTO_TYPE": "baseline_exception",
    "BASELINE_EXCEPTION_DEVICE_DTO_TYPE": "baseline_exception",
    "USER_DTO_TYPE": "baseline_exception",
    "BASELINE_PROFILE_SCHEMA": "baseline_profile",
    "BROWSER_EXTENSION_PERMISSION_SCHEMA": "browser_extension_permission",
    "BROWSER_EXTENSIONS_SCHEMA": "browser_extensions",
    "CONFIGURATION_SCORE_SCHEMA": "configuration_score",
    "DATA_EXPORT_SETTINGS_SCHEMA": "data_export_settings",
    "EVENT_HUB_PROPERTIES_TYPE": "data_export_settings",
    "STORAGE_ACCOUNT_PROPERTIES_TYPE": "data_export_settings",
    "WORKSPACE_PROPERTIES_TYPE": "data_export_settings",
    "DATA_EXPORT_SETTINGS_LOG_DEFINITION_TYPE": "data_export_settings",
    "DELTA_ASSET_VULNERABILITY_SCHEMA": "delta_asset_vulnerability",
    "DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA": "device_authenticated_scan_agent",
    "DEVICE_AUTHENTICATED_SCAN_DEFINITION_SCHEMA": "device_authenticated_scan_definition",
    "AUTH_PARAMS_BASE_TYPE": "device_authenticated_scan_definition",
    "AGENT_CONTRACT_TYPE": "device_authenticated_scan_definition",
    "SCAN_STATE_TYPE": "device_authenticated_scan_definition",
    "ADVANCED_ACTIVE_CONFIGURATION_TYPE": "device_authenticated_scan_definition",
    "DEVICE_AV_INFO_SCHEMA": "device_av_info",
    "DEVICE_GROUP_SCHEMA": "device_group",
    "AAD_USERS_GROUP_TYPE": "device_group",
    "DEVICE_GROUP_PROPERTY_CONDITION_TYPE": "device_group",
    "DEVICE_GROUP_LIST_PROPERTY_CONDITION_TYPE": "device_group",
    "DEVICE_GROUP_RULES_TYPE": "device_group",
    "DLP_MACHINE_SCHEMA": "dlp_machine",
    "DOMAIN_SCHEMA": "domain",
    "EXPORT_FILES_RESPONSE_SCHEMA": "export_files_response",
    "FILE_SCHEMA": "file",
    "FIRMWARE_SCHEMA": "firmware",
    "IN_ORG_DOMAIN_STATS_SCHEMA": "in_org_domain_stats",
    "IN_ORG_FILE_STATS_SCHEMA": "in_org_file_stats",
    "IN_ORG_IP_STATS_SCHEMA": "in_org_ip_stats",
    "INCIDENT_SCHEMA": "incident",
    "VM_METADATA_TYPE": "incident",
    "MTP_DEVICE_TYPE": "incident",
    "MTP_ALERT_EVIDENCE_TYPE": "incident",
    "MTP_ALERT_TYPE": "incident",
    "INDICATOR_SCHEMA": "indicator",
    "CERTIFICATE_INDICATOR_INFORMATION_TYPE": "indicator",
    "INVESTIGATION_SCHEMA": "investigation",
    "IP_SCHEMA": "ip",
    "LIBRARY_FILES_SCHEMA": "library_files",
    "LIST_1_OF_IMPORT_INDICATOR_RESULT_SCHEMA": "list_1_of_import_indicator_result",
    "LIST_1_OF_INDICATOR_SCHEMA": "list_1_of_indicator",
    "MACHINE_SCHEMA": "machine",
    "MACHINE_IP_ADDRESS_TYPE": "machine",
    "MACHINE_ACTION_SCHEMA": "machine_action",
    "RELATED_FILE_INFO_TYPE": "machine_action",
    "CUSTOM_PLAYBOOK_PARAMETER_TYPE": "machine_action",
    "CUSTOM_PLAYBOOK_COMMAND_TYPE": "machine_action",
    "CUSTOM_PLAYBOOK_COMMAND_RESULT_TYPE": "machine_action",
    "TROUBLESHOOT_INFO_TYPE": "machine_action",
    "PUBLIC_ASSET_DTO_SCHEMA": "public_asset_dto",
    "PUBLIC_ASSET_VULNERABILITY_DTO_SCHEMA": "public_asset_vulnerability_dto",
    "PUBLIC_DISTRIBUTION_DTO_SCHEMA": "public_distribution_dto",
    "PUBLIC_PRODUCT_DTO_SCHEMA": "public_product_dto",
    "PUBLIC_PRODUCT_FIX_DTO_SCHEMA": "public_product_fix_dto",
    "PUBLIC_VULNERABILITY_DTO_SCHEMA": "public_vulnerability_dto",
    "RECOMMENDATION_SCHEMA": "recommendation",
    "REMEDIATION_TASK_SCHEMA": "remediation_task",
    "SOFTWARE_SCHEMA": "software",
    "PUBLIC_DISTRIBUTION_DTO_TYPE": "software",
    "USER_SCHEMA": "user",
    "VULNERABILITY_SCHEMA": "vulnerability",
}

_CONTRACT_INDEX: dict[str, dict[str, str]] = {
    "action_availability_status": {
        "name": "mde.action-availability-status.source",
        "schema": "ACTION_AVAILABILITY_STATUS_SCHEMA",
        "version": "1.0.0",
    },
    "alert": {"name": "mde.alert.source", "schema": "ALERT_SCHEMA", "version": "1.0.0"},
    "asset_baseline_assessment": {
        "name": "mde.asset-baseline-assessment.source",
        "schema": "ASSET_BASELINE_ASSESSMENT_SCHEMA",
        "version": "1.0.0",
    },
    "asset_browser_extension": {
        "name": "mde.asset-browser-extension.source",
        "schema": "ASSET_BROWSER_EXTENSION_SCHEMA",
        "version": "1.0.0",
    },
    "asset_certificate_assessment": {
        "name": "mde.asset-certificate-assessment.source",
        "schema": "ASSET_CERTIFICATE_ASSESSMENT_SCHEMA",
        "version": "1.0.0",
    },
    "asset_configuration": {
        "name": "mde.asset-configuration.source",
        "schema": "ASSET_CONFIGURATION_SCHEMA",
        "version": "1.0.0",
    },
    "asset_hardware_firmware": {
        "name": "mde.asset-hardware-firmware.source",
        "schema": "ASSET_HARDWARE_FIRMWARE_SCHEMA",
        "version": "1.0.0",
    },
    "asset_non_cpe_software": {
        "name": "mde.asset-non-cpe-software.source",
        "schema": "ASSET_NON_CPE_SOFTWARE_SCHEMA",
        "version": "1.0.0",
    },
    "asset_software": {
        "name": "mde.asset-software.source",
        "schema": "ASSET_SOFTWARE_SCHEMA",
        "version": "1.1.0",
    },
    "asset_vulnerability": {
        "name": "mde.asset-vulnerability.source",
        "schema": "ASSET_VULNERABILITY_SCHEMA",
        "version": "1.1.0",
    },
    "auth_scan_history_contract": {
        "name": "mde.auth-scan-history-contract.source",
        "schema": "AUTH_SCAN_HISTORY_CONTRACT_SCHEMA",
        "version": "1.0.0",
    },
    "baseline_configuration": {
        "name": "mde.baseline-configuration.source",
        "schema": "BASELINE_CONFIGURATION_SCHEMA",
        "version": "1.0.0",
    },
    "baseline_exception": {
        "name": "mde.baseline-exception.source",
        "schema": "BASELINE_EXCEPTION_SCHEMA",
        "version": "1.0.0",
    },
    "baseline_profile": {
        "name": "mde.baseline-profile.source",
        "schema": "BASELINE_PROFILE_SCHEMA",
        "version": "1.0.0",
    },
    "browser_extension_permission": {
        "name": "mde.browser-extension-permission.source",
        "schema": "BROWSER_EXTENSION_PERMISSION_SCHEMA",
        "version": "1.0.0",
    },
    "browser_extensions": {
        "name": "mde.browser-extensions.source",
        "schema": "BROWSER_EXTENSIONS_SCHEMA",
        "version": "1.0.0",
    },
    "configuration_score": {
        "name": "mde.configuration-score.source",
        "schema": "CONFIGURATION_SCORE_SCHEMA",
        "version": "1.0.0",
    },
    "data_export_settings": {
        "name": "mde.data-export-settings.source",
        "schema": "DATA_EXPORT_SETTINGS_SCHEMA",
        "version": "1.0.0",
    },
    "delta_asset_vulnerability": {
        "name": "mde.delta-asset-vulnerability.source",
        "schema": "DELTA_ASSET_VULNERABILITY_SCHEMA",
        "version": "1.1.0",
    },
    "device_authenticated_scan_agent": {
        "name": "mde.device-authenticated-scan-agent.source",
        "schema": "DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA",
        "version": "1.0.0",
    },
    "device_authenticated_scan_definition": {
        "name": "mde.device-authenticated-scan-definition.source",
        "schema": "DEVICE_AUTHENTICATED_SCAN_DEFINITION_SCHEMA",
        "version": "1.0.0",
    },
    "device_av_info": {
        "name": "mde.device-av-info.source",
        "schema": "DEVICE_AV_INFO_SCHEMA",
        "version": "1.0.0",
    },
    "device_group": {
        "name": "mde.device-group.source",
        "schema": "DEVICE_GROUP_SCHEMA",
        "version": "1.0.0",
    },
    "dlp_machine": {
        "name": "mde.dlp-machine.source",
        "schema": "DLP_MACHINE_SCHEMA",
        "version": "1.0.0",
    },
    "domain": {
        "name": "mde.domain.source",
        "schema": "DOMAIN_SCHEMA",
        "version": "1.0.0",
    },
    "export_files_response": {
        "name": "mde.export-files-response.source",
        "schema": "EXPORT_FILES_RESPONSE_SCHEMA",
        "version": "1.0.0",
    },
    "file": {"name": "mde.file.source", "schema": "FILE_SCHEMA", "version": "1.0.0"},
    "firmware": {
        "name": "mde.firmware.source",
        "schema": "FIRMWARE_SCHEMA",
        "version": "1.0.0",
    },
    "in_org_domain_stats": {
        "name": "mde.in-org-domain-stats.source",
        "schema": "IN_ORG_DOMAIN_STATS_SCHEMA",
        "version": "1.0.0",
    },
    "in_org_file_stats": {
        "name": "mde.in-org-file-stats.source",
        "schema": "IN_ORG_FILE_STATS_SCHEMA",
        "version": "1.0.0",
    },
    "in_org_ip_stats": {
        "name": "mde.in-org-ip-stats.source",
        "schema": "IN_ORG_IP_STATS_SCHEMA",
        "version": "1.0.0",
    },
    "incident": {
        "name": "mde.incident.source",
        "schema": "INCIDENT_SCHEMA",
        "version": "1.0.0",
    },
    "indicator": {
        "name": "mde.indicator.source",
        "schema": "INDICATOR_SCHEMA",
        "version": "1.0.0",
    },
    "investigation": {
        "name": "mde.investigation.source",
        "schema": "INVESTIGATION_SCHEMA",
        "version": "1.0.0",
    },
    "ip": {"name": "mde.ip.source", "schema": "IP_SCHEMA", "version": "1.0.0"},
    "library_files": {
        "name": "mde.library-files.source",
        "schema": "LIBRARY_FILES_SCHEMA",
        "version": "1.0.0",
    },
    "list_1_of_import_indicator_result": {
        "name": "mde.list-1-of-import-indicator-result.source",
        "schema": "LIST_1_OF_IMPORT_INDICATOR_RESULT_SCHEMA",
        "version": "1.0.0",
    },
    "list_1_of_indicator": {
        "name": "mde.list-1-of-indicator.source",
        "schema": "LIST_1_OF_INDICATOR_SCHEMA",
        "version": "1.0.0",
    },
    "machine": {
        "name": "mde.machine.source",
        "schema": "MACHINE_SCHEMA",
        "version": "1.0.0",
    },
    "machine_action": {
        "name": "mde.machine-action.source",
        "schema": "MACHINE_ACTION_SCHEMA",
        "version": "1.0.0",
    },
    "public_asset_dto": {
        "name": "mde.public-asset-dto.source",
        "schema": "PUBLIC_ASSET_DTO_SCHEMA",
        "version": "1.0.0",
    },
    "public_asset_vulnerability_dto": {
        "name": "mde.public-asset-vulnerability-dto.source",
        "schema": "PUBLIC_ASSET_VULNERABILITY_DTO_SCHEMA",
        "version": "1.0.0",
    },
    "public_distribution_dto": {
        "name": "mde.public-distribution-dto.source",
        "schema": "PUBLIC_DISTRIBUTION_DTO_SCHEMA",
        "version": "1.0.0",
    },
    "public_product_dto": {
        "name": "mde.public-product-dto.source",
        "schema": "PUBLIC_PRODUCT_DTO_SCHEMA",
        "version": "1.0.0",
    },
    "public_product_fix_dto": {
        "name": "mde.public-product-fix-dto.source",
        "schema": "PUBLIC_PRODUCT_FIX_DTO_SCHEMA",
        "version": "1.0.0",
    },
    "public_vulnerability_dto": {
        "name": "mde.public-vulnerability-dto.source",
        "schema": "PUBLIC_VULNERABILITY_DTO_SCHEMA",
        "version": "1.0.0",
    },
    "recommendation": {
        "name": "mde.recommendation.source",
        "schema": "RECOMMENDATION_SCHEMA",
        "version": "1.0.0",
    },
    "remediation_task": {
        "name": "mde.remediation-task.source",
        "schema": "REMEDIATION_TASK_SCHEMA",
        "version": "1.0.0",
    },
    "software": {
        "name": "mde.software.source",
        "schema": "SOFTWARE_SCHEMA",
        "version": "1.0.0",
    },
    "user": {"name": "mde.user.source", "schema": "USER_SCHEMA", "version": "1.0.0"},
    "vulnerability": {
        "name": "mde.vulnerability.source",
        "schema": "VULNERABILITY_SCHEMA",
        "version": "1.0.0",
    },
}


def __getattr__(name: str) -> object:
    slug = _NAME_TO_SLUG.get(name)
    if slug is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(f".{slug}.schema", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


__all__ = [
    "AAD_USERS_GROUP_TYPE",
    "ACTION_AVAILABILITY_STATUS_SCHEMA",
    "ADVANCED_ACTIVE_CONFIGURATION_TYPE",
    "AGENT_CONTRACT_TYPE",
    "ALERT_COMMENT_TYPE",
    "ALERT_EVIDENCE_TYPE",
    "ALERT_RELATED_USER_TYPE",
    "ALERT_SCHEMA",
    "ASSET_BASELINE_ASSESSMENT_SCHEMA",
    "ASSET_BROWSER_EXTENSION_SCHEMA",
    "ASSET_CERTIFICATE_ASSESSMENT_SCHEMA",
    "ASSET_CONFIGURATION_SCHEMA",
    "ASSET_HARDWARE_FIRMWARE_SCHEMA",
    "ASSET_NON_CPE_SOFTWARE_SCHEMA",
    "ASSET_SOFTWARE_SCHEMA",
    "ASSET_VULNERABILITY_SCHEMA",
    "AUTH_PARAMS_BASE_TYPE",
    "AUTH_SCAN_HISTORY_CONTRACT_SCHEMA",
    "BASELINE_CONFIGURATION_DTO_TYPE",
    "BASELINE_CONFIGURATION_SCHEMA",
    "BASELINE_EXCEPTION_DEVICE_DTO_TYPE",
    "BASELINE_EXCEPTION_SCHEMA",
    "BASELINE_PROFILE_SCHEMA",
    "BROWSER_EXTENSIONS_SCHEMA",
    "BROWSER_EXTENSION_PERMISSION_SCHEMA",
    "CERTIFICATE_INDICATOR_INFORMATION_TYPE",
    "CONFIGURATION_SCORE_SCHEMA",
    "CUSTOM_PLAYBOOK_COMMAND_RESULT_TYPE",
    "CUSTOM_PLAYBOOK_COMMAND_TYPE",
    "CUSTOM_PLAYBOOK_PARAMETER_TYPE",
    "DATA_EXPORT_SETTINGS_LOG_DEFINITION_TYPE",
    "DATA_EXPORT_SETTINGS_SCHEMA",
    "DELTA_ASSET_VULNERABILITY_SCHEMA",
    "DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA",
    "DEVICE_AUTHENTICATED_SCAN_DEFINITION_SCHEMA",
    "DEVICE_AV_INFO_SCHEMA",
    "DEVICE_GROUP_LIST_PROPERTY_CONDITION_TYPE",
    "DEVICE_GROUP_PROPERTY_CONDITION_TYPE",
    "DEVICE_GROUP_RULES_TYPE",
    "DEVICE_GROUP_SCHEMA",
    "DLP_MACHINE_SCHEMA",
    "DOMAIN_SCHEMA",
    "DOMAIN_TYPE",
    "EVENT_HUB_PROPERTIES_TYPE",
    "EXPORT_FILES_RESPONSE_SCHEMA",
    "FILE_SCHEMA",
    "FIRMWARE_SCHEMA",
    "INCIDENT_SCHEMA",
    "INDICATOR_SCHEMA",
    "INVESTIGATION_SCHEMA",
    "IN_ORG_DOMAIN_STATS_SCHEMA",
    "IN_ORG_FILE_STATS_SCHEMA",
    "IN_ORG_IP_STATS_SCHEMA",
    "IP_SCHEMA",
    "LIBRARY_FILES_SCHEMA",
    "LIST_1_OF_IMPORT_INDICATOR_RESULT_SCHEMA",
    "LIST_1_OF_INDICATOR_SCHEMA",
    "LOGGED_ON_USER_TYPE",
    "MACHINE_ACTION_SCHEMA",
    "MACHINE_IP_ADDRESS_TYPE",
    "MACHINE_SCHEMA",
    "MTP_ALERT_EVIDENCE_TYPE",
    "MTP_ALERT_TYPE",
    "MTP_DEVICE_TYPE",
    "PUBLIC_ASSET_DTO_SCHEMA",
    "PUBLIC_ASSET_VULNERABILITY_DTO_SCHEMA",
    "PUBLIC_DISTRIBUTION_DTO_SCHEMA",
    "PUBLIC_DISTRIBUTION_DTO_TYPE",
    "PUBLIC_PRODUCT_DTO_SCHEMA",
    "PUBLIC_PRODUCT_FIX_DTO_SCHEMA",
    "PUBLIC_VULNERABILITY_DTO_SCHEMA",
    "RECOMMENDATION_SCHEMA",
    "RELATED_FILE_INFO_TYPE",
    "REMEDIATION_TASK_SCHEMA",
    "SCANNED_TARGET_RESULT_CONTRACT_TYPE",
    "SCAN_STATE_TYPE",
    "SOFTWARE_SCHEMA",
    "STORAGE_ACCOUNT_PROPERTIES_TYPE",
    "TROUBLESHOOT_INFO_TYPE",
    "USER_DTO_TYPE",
    "USER_SCHEMA",
    "VM_METADATA_TYPE",
    "VULNERABILITY_SCHEMA",
    "WORKSPACE_PROPERTIES_TYPE",
]
