# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

LIBRARY_FILES_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("fileName", pa.string(), nullable=False),
        pa.field("sha256", pa.string()),
        pa.field("description", pa.string()),
        pa.field("creationTime", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("lastUpdatedTime", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("createdBy", pa.string()),
        pa.field("hasParameters", pa.bool_(), nullable=False),
        pa.field("parametersDescription", pa.string()),
    ]
)
