# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

IN_ORG_DOMAIN_STATS_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("host", pa.string()),
        pa.field("orgPrevalence", pa.string()),
        pa.field("orgFirstSeen", pa.timestamp("us", tz="UTC")),
        pa.field("orgLastSeen", pa.timestamp("us", tz="UTC")),
        pa.field("organizationPrevalence", pa.int32()),
    ]
)
