# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

PUBLIC_PRODUCT_DTO_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("name", pa.string()),
        pa.field("vendor", pa.string()),
        pa.field("weaknesses", pa.int64(), nullable=False),
        pa.field("publicExploit", pa.bool_(), nullable=False),
        pa.field("activeAlert", pa.bool_(), nullable=False),
        pa.field("exposedMachines", pa.int64(), nullable=False),
        pa.field("installedMachines", pa.int64(), nullable=False),
        pa.field("impactScore", pa.float32(), nullable=False),
        pa.field("isNormalized", pa.bool_(), nullable=False),
        pa.field("category", pa.string()),
        pa.field("tags", pa.list_(pa.string())),
    ]
)
