# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("machineId", pa.string()),
        pa.field("lastSeen", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("computerDnsName", pa.string()),
        pa.field("assignedApplicationId", pa.string()),
        pa.field("scannerSoftwareVersion", pa.string()),
        pa.field(
            "lastCommandExecutionTimestamp",
            pa.timestamp("us", tz="UTC"),
            nullable=False,
        ),
        pa.field("mdeClientVersion", pa.string()),
    ]
)
