#!/usr/bin/env python3
"""MDE Arrow Schema Contract Builder

Reads   tests/mde_client/fixtures/mde_metadata.xml
Writes  src/mde_client/schemas/<type_snake>.py     (one file per top-level response type)
    src/mde_client/schemas/__init__.py         (re-exports everything, lazily)

Each generated schema file contains:
  - Named pa.StructType constants for every ComplexType dependency,
    topologically sorted so each constant is defined before it is referenced.
  - A single <ENTITY_UPPER>_SCHEMA: pa.Schema constant at the bottom.

The generated files match the hand-written style of schemas/machines.py:
  - Enums          → pa.string()                    (API returns human-readable strings)
  - DateTimeOffset → pa.timestamp("us", tz="UTC")   (microsecond precision, UTC-aware)
  - NavigationProperties excluded                    (relationship links, not columns)
  - Abstract ComplexTypes → pa.string()             (polymorphic, can't inline safely)

After writing all files, runs `just quality-schema` so the output is always
commit-ready — lint, format, typecheck, and tests all pass before exit.

Usage (from project root):
    just schema-build       # Build schemas if XML is stale or missing, then run quality gate
    just schema-build-dry   # Same, but print generated source to stdout instead of writing files
    just schema-refresh     # Fetch fresh $metadata from the API and write to XML_SOURCE, then exit (no generation)
    just schema-refresh-dry # Same, but print XML to stdout instead of writing file
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path

import pyarrow as pa

# ── Configuration ─────────────────────────────────────────────────────────────

XML_SOURCE = Path("tests/mde_client/fixtures/mde_metadata.xml")
OUTPUT_DIR = Path("src/mde_client/schemas")
MODELS_OUTPUT_DIR = Path("src/mde_client/models")
METADATA_MAX_AGE = timedelta(days=7)

MDE_NS = "http://docs.oasis-open.org/odata/ns/edm"
MDE_API_PREFIX = "microsoft.windowsDefenderATP.api."

_GENERATED_HEADER = "# AUTO-GENERATED by scripts/mde_contract.py"

# OData primitive → (pa.DataType, source expression).
#
# The pa.DataType half is the single source of truth — ty/pyright validate it
# and the test validator uses it directly for comparisons.
# The str half is emitted verbatim into generated .py files by _type_expr().
# Keeping them together means they can never silently drift apart.
EDM_PA_TYPES: dict[str, tuple[pa.DataType, str]] = {
    "Edm.String": (pa.string(), "pa.string()"),
    "Edm.Int16": (pa.int16(), "pa.int16()"),
    "Edm.Int32": (pa.int32(), "pa.int32()"),
    "Edm.Int64": (pa.int64(), "pa.int64()"),
    "Edm.Boolean": (pa.bool_(), "pa.bool_()"),
    "Edm.Double": (pa.float64(), "pa.float64()"),
    "Edm.Single": (pa.float32(), "pa.float32()"),
    "Edm.Byte": (pa.uint8(), "pa.uint8()"),
    "Edm.SByte": (pa.int8(), "pa.int8()"),
    "Edm.Guid": (pa.string(), "pa.string()"),
    "Edm.DateTimeOffset": (
        pa.timestamp("us", tz="UTC"),
        'pa.timestamp("us", tz="UTC")',
    ),
    "Edm.Duration": (pa.duration("us"), 'pa.duration("us")'),
    "Edm.TimeOfDay": (pa.time64("us"), 'pa.time64("us")'),
    "Edm.Binary": (pa.large_binary(), "pa.large_binary()"),
}

# EntityTypes to skip — action parameter wrappers, not query-able resources
SKIP_ENTITIES: set[str] = {
    "PostDeviceGroupsRequest",
}

# Bound actions that omit ReturnType in the published metadata but still return
# contract-defined payload shapes at runtime. The override value is the XML
# type name that should be treated as the response root for schema generation.
NO_RETURN_ACTION_RESPONSE_OVERRIDES: dict[tuple[str, str], str] = {
    (
        "GetScanHistoryBySessionId",
        "Collection(microsoft.windowsDefenderATP.api.DeviceAuthenticatedScanDefinition)",
    ): "AuthScanHistoryContract",
    (
        "GetScanHistoryByScanDefinitionId",
        "Collection(microsoft.windowsDefenderATP.api.DeviceAuthenticatedScanDefinition)",
    ): "AuthScanHistoryContract",
}


@dataclass(frozen=True)
class RequestModelSpec:
    module: str
    base_model: str
    union_name: str
    discriminator: str


@dataclass(frozen=True)
class ActionParam:
    """Parsed non-binding parameter from an OData Action element."""

    name: str
    odata_type: str
    nullable: bool
    optional: bool  # has Org.OData.Core.V1.OptionalParameter annotation


@dataclass(frozen=True)
class ActionPayloadSpec:
    """Generate a Pydantic BasePayload from bound action parameters."""

    action_name: str
    class_name: str
    binding_type: str  # full OData type of the binding parameter


@dataclass(frozen=True)
class SupportModuleSpec:
    """One generated support-model module under src/mde_client/models/."""

    enums: dict[str, str]  # XML enum name → Python alias name (UPPER_SNAKE)
    action_payloads: list[ActionPayloadSpec]


# Narrow, opt-in request-model generation for contract-defined request payload
# shapes that we do not want to hand-maintain in endpoint modules.
REQUEST_MODEL_SPECS: dict[str, RequestModelSpec] = {
    "AuthParamsBase": RequestModelSpec(
        module="auth_params_models",
        base_model="_AuthParamsBase",
        union_name="SCANAUTHENTICATIONPARAMS",
        discriminator="type",
    ),
}

REQUEST_MODEL_PRIMITIVES: dict[str, str] = {
    "Edm.String": "str",
    "Edm.Int16": "int",
    "Edm.Int32": "int",
    "Edm.Int64": "int",
    "Edm.Boolean": "bool",
    "Edm.Double": "float",
    "Edm.Single": "float",
    "Edm.Byte": "int",
    "Edm.SByte": "int",
    "Edm.Guid": "str",
}

# Narrow, opt-in support-model generation for contract-derived enum aliases
# and action payload models that we do not want to hand-maintain.
SUPPORT_MODULE_SPECS: dict[str, SupportModuleSpec] = {
    "investigation_models": SupportModuleSpec(
        enums={
            "InvestigationState": "INVESTIGATION_STATE",
            "KnownRequestSource": "KNOWN_REQUEST_SOURCE",
        },
        action_payloads=[
            ActionPayloadSpec(
                action_name="StartInvestigation",
                class_name="InvestigationStartPayload",
                binding_type="microsoft.windowsDefenderATP.api.Machine",
            ),
        ],
    ),
}


# ── Naming helpers ────────────────────────────────────────────────────────────


def camel_to_snake(name: str) -> str:
    """MachineAction → machine_action"""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def to_const(name: str) -> str:
    """MachineAction → MACHINE_ACTION"""
    return camel_to_snake(name).upper()


def strip_prefix(odata_type: str) -> str:
    """'microsoft.windowsDefenderATP.api.Alert' → 'Alert'"""
    if odata_type.startswith(MDE_API_PREFIX):
        return odata_type[len(MDE_API_PREFIX) :]
    return odata_type


def unwrap_collection(odata_t: str) -> str:
    if odata_t.startswith("Collection("):
        return odata_t[len("Collection(") : -1]
    return odata_t


# ── Quality gate ──────────────────────────────────────────────────────────────


def run_quality() -> None:
    """Run `just quality-schema` so generated files are lint-, format-, and type-clean."""
    result = subprocess.run(["just", "quality-schema"])
    if result.returncode != 0:
        raise SystemExit(result.returncode)


# ── Metadata fetcher ──────────────────────────────────────────────────────────


def fetch_metadata() -> None:
    """Fetch fresh $metadata from the MDE API and write it to XML_SOURCE."""
    from mde_client import MDEClient

    client = MDEClient(
        tenant_id=os.environ["AZURE_TENANT_ID"],
        client_id=os.environ["AZURE_CLIENT_ID"],
        client_secret=os.environ["AZURE_CLIENT_SECRET"],
    )

    print("Fetching MDE $metadata from API...")
    response = client.misc._request("GET", "api/$metadata")
    response.raise_for_status()

    XML_SOURCE.parent.mkdir(parents=True, exist_ok=True)
    XML_SOURCE.write_bytes(response.content)
    print(f"  ✓ saved to {XML_SOURCE}")


def metadata_is_stale() -> bool:
    """True when XML_SOURCE is missing or older than METADATA_MAX_AGE."""
    if not XML_SOURCE.exists():
        return True
    age = datetime.now() - datetime.fromtimestamp(XML_SOURCE.stat().st_mtime)
    return age > METADATA_MAX_AGE


# ── Stale file cleanup ────────────────────────────────────────────────────────


def cleanup_stale_schemas(expected_paths: set[Path]) -> None:
    """Remove AUTO-GENERATED schema files that are no longer in the expected set.

    Only removes files whose first line contains the generated header — hand-written
    files (e.g. the old machines.py) are never touched.
    """
    for path in sorted(OUTPUT_DIR.glob("*.py")):
        if path.name == "__init__.py":
            continue
        if path in expected_paths:
            continue
        try:
            first_line = path.read_text(encoding="utf-8").split("\n", 1)[0]
        except OSError:
            continue
        if _GENERATED_HEADER in first_line:
            path.unlink()
            print(f"  🗑  removed stale {path.name}")


# ── Metadata parser ───────────────────────────────────────────────────────────


class MDEMetadata:
    """Parses the MDE OData CSDL XML into typed registries."""

    def __init__(self, path: Path) -> None:
        root = ET.parse(path).getroot()

        self.enum_types: set[str] = set()
        self.enum_members: dict[str, list[str]] = {}
        self.abstract_types: set[str] = set()
        # short name → list of <Property> elements (no <NavigationProperty>)
        self.complex_types: dict[str, list[ET.Element]] = {}
        self.entity_types: dict[str, list[ET.Element]] = {}
        self.response_complex_types: set[str] = set()
        # child short name → parent short name
        self.base_types: dict[str, str] = {}
        # action name → list of non-binding ActionParam
        self.actions: dict[str, list[ActionParam]] = {}

        for el in root.iter(f"{{{MDE_NS}}}EnumType"):
            name = el.get("Name", "")
            self.enum_types.add(name)
            self.enum_members[name] = [
                member.get("Name", "")
                for member in el.findall(f"{{{MDE_NS}}}Member")
                if member.get("Name")
            ]

        for el in root.iter(f"{{{MDE_NS}}}ComplexType"):
            name = el.get("Name", "")
            self.complex_types[name] = el.findall(f"{{{MDE_NS}}}Property")
            if el.get("Abstract", "false").lower() == "true":
                self.abstract_types.add(name)
            if base := el.get("BaseType"):
                self.base_types[name] = strip_prefix(base)

        for el in root.iter(f"{{{MDE_NS}}}EntityType"):
            name = el.get("Name", "")
            # NavigationProperties intentionally excluded — relationship links
            # resolved server-side, not columns returned in the response body.
            self.entity_types[name] = el.findall(f"{{{MDE_NS}}}Property")
            if el.get("Abstract", "false").lower() == "true":
                self.abstract_types.add(name)
            if base := el.get("BaseType"):
                self.base_types[name] = strip_prefix(base)

        for kind in ("Function", "Action"):
            for el in root.iter(f"{{{MDE_NS}}}{kind}"):
                action_name = el.get("Name", "")

                # ── Action parameter capture ─────────────────────────────
                params: list[ActionParam] = []
                for param_el in el.findall(f"{{{MDE_NS}}}Parameter"):
                    pname = param_el.get("Name", "")
                    if pname == "bindingParameter":
                        continue
                    has_optional = (
                        param_el.find(
                            f"{{{MDE_NS}}}Annotation[@Term='Org.OData.Core.V1.OptionalParameter']"
                        )
                        is not None
                    )
                    params.append(
                        ActionParam(
                            name=pname,
                            odata_type=param_el.get("Type", "Edm.String"),
                            nullable=param_el.get("Nullable", "true").lower()
                            != "false",
                            optional=has_optional,
                        )
                    )
                if params:
                    self.actions[action_name] = params

                # ── Response complex type capture ────────────────────────
                return_el = el.find(f"{{{MDE_NS}}}ReturnType")
                if return_el is None:
                    binding_el = el.find(
                        f"{{{MDE_NS}}}Parameter[@Name='bindingParameter']"
                    )
                    binding_type = (
                        binding_el.get("Type", "") if binding_el is not None else ""
                    )
                    override_key = (el.get("Name", ""), binding_type)
                    override_type = NO_RETURN_ACTION_RESPONSE_OVERRIDES.get(
                        override_key
                    )
                    if override_type is None:
                        continue
                    return_type = override_type
                else:
                    return_type = return_el.get("Type", "")

                short_name = strip_prefix(unwrap_collection(return_type))

                if (
                    short_name in self.complex_types
                    and short_name not in self.abstract_types
                ):
                    self.response_complex_types.add(short_name)

    def props_for(self, type_name: str) -> list[ET.Element]:
        """Return flattened (inherited → own) Property elements for any type name."""
        chain: list[str] = []
        cursor = type_name
        while parent := self.base_types.get(cursor):
            chain.append(parent)
            cursor = parent

        props: list[ET.Element] = []
        for ancestor in reversed(chain):
            props += (
                self.entity_types.get(ancestor)
                or self.complex_types.get(ancestor)
                or []
            )
        props += (
            self.entity_types.get(type_name) or self.complex_types.get(type_name) or []
        )
        return props

    def declared_props_for(self, type_name: str) -> list[ET.Element]:
        """Return only properties declared directly on *type_name*."""
        return (
            self.entity_types.get(type_name) or self.complex_types.get(type_name) or []
        )

    def concrete_descendants(self, abstract_name: str) -> list[str]:
        """Return concrete ComplexType names that directly derive from *abstract_name*."""
        return [
            child
            for child, parent in self.base_types.items()
            if parent == abstract_name
            and child in self.complex_types
            and child not in self.abstract_types
        ]

    def _normalize_odata_for_compat(self, odata_t: str) -> str:
        """Normalize an OData type for Arrow-level compatibility comparison.

        Different enum type names all map to ``pa.string()``, so they are
        treated as equivalent for merge-safety checks.
        """
        if odata_t.startswith("Collection("):
            inner = odata_t[len("Collection(") : -1]
            return f"Collection({self._normalize_odata_for_compat(inner)})"
        short = strip_prefix(odata_t)
        if short in self.enum_types:
            return "Edm.String"
        return odata_t

    def can_merge_abstract(self, abstract_name: str) -> bool:
        """True when all concrete descendants share compatible field types.

        "Compatible" means every field name that appears in more than one
        descendant maps to the same Arrow type.  When this holds the
        descendants can be flattened into a single nullable Arrow struct.
        """
        descendants = self.concrete_descendants(abstract_name)
        if not descendants:
            return False

        field_types: dict[str, str] = {}
        for desc in descendants:
            for prop in self.props_for(desc):
                name = prop.get("Name", "")
                odata_t = self._normalize_odata_for_compat(prop.get("Type", ""))
                if name in field_types and field_types[name] != odata_t:
                    return False
                field_types[name] = odata_t
        return True

    def merged_abstract_props(self, abstract_name: str) -> list[ET.Element]:
        """Return the union of properties across base + all concrete descendants.

        Every field is made nullable in the merged view because any given
        response will only populate the subset for its concrete subtype.
        Ordering: base fields first, then descendant-only fields in
        discovery order.
        """
        seen_names: set[str] = set()
        merged: list[ET.Element] = []

        for prop in self.props_for(abstract_name):
            name = prop.get("Name", "")
            if name not in seen_names:
                seen_names.add(name)
                merged.append(prop)

        for desc in self.concrete_descendants(abstract_name):
            for prop in self.props_for(desc):
                name = prop.get("Name", "")
                if name not in seen_names:
                    seen_names.add(name)
                    merged.append(prop)

        return merged

    def referenced_complex_types(
        self, type_name: str, _seen: set[str] | None = None
    ) -> list[str]:
        """Return all ComplexType short names transitively reachable from type_name.

        Returns in dependency order so constants can be emitted without
        forward-reference issues.  Mergeable abstract types and their
        concrete descendants are included so the emitter can produce the
        merged struct constant.
        """
        if _seen is None:
            _seen = set()
        result: list[str] = []
        for prop in self.props_for(type_name):
            raw = prop.get("Type", "")
            short = strip_prefix(unwrap_collection(raw))
            if short in self.complex_types and short not in _seen:
                _seen.add(short)
                # If abstract and mergeable, pull in descendants too
                if short in self.abstract_types and self.can_merge_abstract(short):
                    for desc in self.concrete_descendants(short):
                        if desc not in _seen:
                            _seen.add(desc)
                            result.extend(self.referenced_complex_types(desc, _seen))
                result.extend(self.referenced_complex_types(short, _seen))
                result.append(short)
        return result


# ── Code generator ────────────────────────────────────────────────────────────


class SchemaCodeGen:
    def __init__(self, meta: MDEMetadata) -> None:
        self.meta = meta

    # -- Type expression -------------------------------------------------------

    def _type_expr(self, odata_t: str) -> str:
        """Resolve an OData type string to a PyArrow source expression string."""
        if odata_t.startswith("Collection("):
            inner = odata_t[len("Collection(") : -1]
            return f"pa.list_({self._type_expr(inner)})"

        if odata_t in EDM_PA_TYPES:
            _, expr = EDM_PA_TYPES[odata_t]
            return expr

        short = strip_prefix(odata_t)

        if short in self.meta.enum_types:
            return "pa.string()"

        if short in self.meta.complex_types:
            if short in self.meta.abstract_types:
                if self.meta.can_merge_abstract(short):
                    return f"{to_const(short)}_TYPE"
                return "pa.string()"
            return f"{to_const(short)}_TYPE"

        return "pa.string()"

    # -- Field line ------------------------------------------------------------

    def _field_line(self, prop: ET.Element, indent: int = 8) -> str:
        name = prop.get("Name", "")
        odata_t = prop.get("Type", "Edm.String")
        nullable = prop.get("Nullable", "true").lower() != "false"
        pad = " " * indent
        type_expr = self._type_expr(odata_t)
        if nullable:
            return f'{pad}pa.field("{name}", {type_expr}),'
        return f'{pad}pa.field("{name}", {type_expr}, nullable=False),'

    # -- Struct constant block -------------------------------------------------

    def _struct_block(self, ct_name: str) -> str:
        const = f"{to_const(ct_name)}_TYPE"
        lines = [f"{const}: pa.StructType = pa.struct("]
        lines += ["    ["]

        if ct_name in self.meta.abstract_types and self.meta.can_merge_abstract(
            ct_name
        ):
            # Merged abstract struct: union of base + descendant fields, all nullable
            for prop in self.meta.merged_abstract_props(ct_name):
                name = prop.get("Name", "")
                odata_t = prop.get("Type", "Edm.String")
                pad = " " * 8
                type_expr = self._type_expr(odata_t)
                lines.append(f'{pad}pa.field("{name}", {type_expr}),')
        else:
            for prop in self.meta.props_for(ct_name):
                lines.append(self._field_line(prop, indent=8))

        lines += ["    ]", ")"]
        return "\n".join(lines)

    # -- Schema constant block -------------------------------------------------

    def _schema_block(self, type_name: str) -> str:
        const = f"{to_const(type_name)}_SCHEMA"
        lines = [f"{const}: pa.Schema = pa.schema("]
        lines += ["    ["]
        for prop in self.meta.props_for(type_name):
            lines.append(self._field_line(prop, indent=8))
        lines += ["    ]", ")"]
        return "\n".join(lines)

    # -- Schema file -----------------------------------------------------------

    def generate(self, type_name: str) -> str:
        """Generate the full source for one schema .py file."""
        dep_structs = self.meta.referenced_complex_types(type_name)

        header_lines = [
            "# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.",
            "# Re-run the script to regenerate when MDE $metadata changes.",
            "import pyarrow as pa",
        ]

        parts: list[str] = ["\n".join(header_lines), ""]

        if dep_structs:
            parts.append("\n\n".join(self._struct_block(ct) for ct in dep_structs))
            parts.append("")

        parts.append(self._schema_block(type_name))
        parts.append("")  # trailing newline

        return "\n".join(parts)

    # -- __init__.py -----------------------------------------------------------

    def _exports_for(self, type_name: str) -> list[str]:
        """_SCHEMA first, then non-abstract _TYPE deps in topological order.

        Mergeable abstract types are also exported since they produce a
        concrete struct constant.
        """
        exports: list[str] = [f"{to_const(type_name)}_SCHEMA"]
        seen: set[str] = {exports[0]}
        for ct_name in self.meta.referenced_complex_types(type_name):
            if ct_name not in self.meta.abstract_types or self.meta.can_merge_abstract(
                ct_name
            ):
                const = f"{to_const(ct_name)}_TYPE"
                if const not in seen:
                    seen.add(const)
                    exports.append(const)
        return exports

    def generate_init(self, type_names: list[str]) -> str:
        """Generate schemas/__init__.py with PEP 562 lazy loading."""
        name_to_module: dict[str, str] = {}
        for type_name in type_names:
            module = camel_to_snake(type_name)
            for export in self._exports_for(type_name):
                if export not in name_to_module:
                    name_to_module[export] = module

        seen_modules: dict[str, list[str]] = {}
        for name, module in name_to_module.items():
            seen_modules.setdefault(module, []).append(name)

        type_checking_lines: list[str] = []
        for module, names in seen_modules.items():
            if len(names) == 1:
                type_checking_lines.append(f"    from .{module} import {names[0]}")
            else:
                joined = ",\n        ".join(names)
                type_checking_lines.append(
                    f"    from .{module} import (\n        {joined},\n    )"
                )

        registry_lines: list[str] = ["_NAME_TO_MODULE: dict[str, str] = {"]
        for name, module in name_to_module.items():
            registry_lines.append(f'    "{name}": "{module}",')
        registry_lines.append("}")

        all_entries = ",\n    ".join(f'"{n}"' for n in sorted(name_to_module))

        lines: list[str] = [
            "# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.",
            "# Re-run the script to regenerate when MDE $metadata changes.",
            "from __future__ import annotations",
            "",
            "import importlib",
            "from typing import TYPE_CHECKING",
            "",
            "if TYPE_CHECKING:",
            *type_checking_lines,
            "",
            *registry_lines,
            "",
            "",
            "def __getattr__(name: str) -> object:",
            '    """Lazily import schema constants on first access (PEP 562).',
            "",
            "    The resolved value is written back into the module's globals so",
            "    subsequent accesses skip this function entirely.",
            '    """',
            "    module_name = _NAME_TO_MODULE.get(name)",
            "    if module_name is None:",
            '        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")',
            "    module = importlib.import_module(f'.{module_name}', __name__)",
            "    value = getattr(module, name)",
            "    globals()[name] = value  # cache: subsequent access bypasses __getattr__",
            "    return value",
            "",
            "",
            "__all__ = [",
            f"    {all_entries},",
            "]",
            "",
        ]

        return "\n".join(lines)


class RequestModelCodeGen:
    def __init__(self, meta: MDEMetadata) -> None:
        self.meta = meta

    def _literal_block(self, enum_name: str) -> str:
        members = self.meta.enum_members[enum_name]
        joined = ", ".join(f'"{member}"' for member in members)
        return f"{to_const(enum_name)} = Literal[{joined}]"

    def _python_type_expr(self, odata_t: str) -> str:
        if odata_t.startswith("Collection("):
            inner = odata_t[len("Collection(") : -1]
            return f"list[{self._python_type_expr(inner)}]"

        if odata_t in REQUEST_MODEL_PRIMITIVES:
            return REQUEST_MODEL_PRIMITIVES[odata_t]

        short = strip_prefix(odata_t)

        if short in self.meta.enum_types:
            return to_const(short)
        if short in self.meta.complex_types:
            return short

        raise ValueError(f"Unsupported request-model field type: {odata_t}")

    def _field_line(self, prop: ET.Element, indent: int = 4) -> str:
        name = prop.get("Name", "")
        odata_t = prop.get("Type", "Edm.String")
        nullable = prop.get("Nullable", "true").lower() != "false"
        py_type = self._python_type_expr(odata_t)
        pad = " " * indent

        if nullable:
            return f"{pad}{name}: {py_type} | None = None"
        if odata_t == "Edm.Boolean":
            return f"{pad}{name}: bool = False"
        return f"{pad}{name}: {py_type}"

    def _enum_names_for(self, type_names: list[str]) -> list[str]:
        enum_names: list[str] = []
        seen: set[str] = set()
        for type_name in type_names:
            for prop in self.meta.declared_props_for(type_name):
                short = strip_prefix(unwrap_collection(prop.get("Type", "")))
                if short in self.meta.enum_types and short not in seen:
                    seen.add(short)
                    enum_names.append(short)
        return enum_names

    def _model_block(
        self,
        model_name: str,
        base_name: str,
        props: list[ET.Element],
        *,
        base_model: bool = False,
    ) -> str:
        lines = [f"class {model_name}({base_name}):"]
        if base_model:
            lines.append('    model_config = {"extra": "forbid"}')
            lines.append("")
        for prop in props:
            lines.append(self._field_line(prop))
        return "\n".join(lines)

    def generate(self, root_name: str, spec: RequestModelSpec) -> str:
        descendants = self.meta.concrete_descendants(root_name)
        enum_names = self._enum_names_for([root_name, *descendants])

        parts: list[str] = [
            "# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.",
            "# Re-run the script to regenerate when MDE $metadata changes.",
            "from __future__ import annotations",
            "",
            "from typing import Annotated, Literal",
            "",
            "from pydantic import BaseModel, Field",
            "",
        ]

        if enum_names:
            parts.append("\n".join(self._literal_block(name) for name in enum_names))
            parts.append("")

        parts.append(
            self._model_block(
                spec.base_model,
                "BaseModel",
                self.meta.declared_props_for(root_name),
                base_model=True,
            )
        )
        parts.append("")

        for descendant in descendants:
            parts.append(
                self._model_block(
                    descendant,
                    spec.base_model,
                    self.meta.declared_props_for(descendant),
                )
            )
            parts.append("")

        union_expr = " | ".join(descendants)
        parts.append(
            f"{spec.union_name} = Annotated[\n"
            f"    {union_expr},\n"
            f'    Field(discriminator="{spec.discriminator}"),\n'
            "]"
        )
        parts.append("")

        all_entries = [
            *(to_const(enum_name) for enum_name in enum_names),
            *descendants,
            spec.union_name,
        ]
        parts.append("__all__ = [")
        parts.extend(f'    "{entry}",' for entry in all_entries)
        parts.append("]")
        parts.append("")

        return "\n".join(parts)


class SupportModelCodeGen:
    """Generates non-Arrow support models: enum Literal aliases and action payload classes."""

    def __init__(self, meta: MDEMetadata) -> None:
        self.meta = meta

    def _literal_block(self, enum_name: str, alias_name: str) -> str:
        members = self.meta.enum_members[enum_name]
        joined = ", ".join(f'"{m}"' for m in members)
        return f"{alias_name} = Literal[{joined}]"

    def _python_type_expr(self, odata_t: str, enum_aliases: dict[str, str]) -> str:
        if odata_t.startswith("Collection("):
            inner = odata_t[len("Collection(") : -1]
            return f"list[{self._python_type_expr(inner, enum_aliases)}]"
        if odata_t in REQUEST_MODEL_PRIMITIVES:
            return REQUEST_MODEL_PRIMITIVES[odata_t]
        short = strip_prefix(odata_t)
        if short in enum_aliases:
            return enum_aliases[short]
        if short in self.meta.enum_types:
            return "str"
        return "str"

    def _action_payload_block(
        self, spec: ActionPayloadSpec, enum_aliases: dict[str, str]
    ) -> str:
        params = self.meta.actions.get(spec.action_name, [])
        lines = [f"class {spec.class_name}(BasePayload):"]
        if not params:
            lines.append("    pass")
            return "\n".join(lines)

        for p in params:
            py_type = self._python_type_expr(p.odata_type, enum_aliases)
            if p.optional:
                lines.append(f"    {p.name}: {py_type} | None = None")
            else:
                lines.append(f"    {p.name}: {py_type}")
        return "\n".join(lines)

    def _collect_enum_deps(self, spec: SupportModuleSpec) -> dict[str, str]:
        """Collect all enum aliases needed: explicit + transitive from action params."""
        aliases: dict[str, str] = dict(spec.enums)
        for ap in spec.action_payloads:
            for p in self.meta.actions.get(ap.action_name, []):
                short = strip_prefix(unwrap_collection(p.odata_type))
                if short in self.meta.enum_types and short not in aliases:
                    aliases[short] = to_const(short)
        return aliases

    def generate(self, module_name: str, spec: SupportModuleSpec) -> str:
        enum_aliases = self._collect_enum_deps(spec)

        parts: list[str] = [
            "# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.",
            "# Re-run the script to regenerate when MDE $metadata changes.",
            "from __future__ import annotations",
            "",
            "from typing import Literal",
            "",
        ]

        needs_base_payload = bool(spec.action_payloads)
        if needs_base_payload:
            parts.append("from mde_client.endpoints.base import BasePayload")
            parts.append("")

        if enum_aliases:
            parts.append(
                "\n".join(
                    self._literal_block(name, alias)
                    for name, alias in enum_aliases.items()
                )
            )
            parts.append("")

        for ap_spec in spec.action_payloads:
            parts.append("")
            parts.append(self._action_payload_block(ap_spec, enum_aliases))
            parts.append("")

        all_entries: list[str] = [*enum_aliases.values()]
        for ap_spec in spec.action_payloads:
            all_entries.append(ap_spec.class_name)

        parts.append("__all__ = [")
        parts.extend(f'    "{entry}",' for entry in all_entries)
        parts.append("]")
        parts.append("")

        return "\n".join(parts)

    def generate_init(self, module_specs: dict[str, SupportModuleSpec]) -> str:
        """Generate models/__init__.py with PEP 562 lazy loading."""
        name_to_module: dict[str, str] = {}
        for module_name, spec in module_specs.items():
            enum_aliases = self._collect_enum_deps(spec)
            for alias in enum_aliases.values():
                name_to_module[alias] = module_name
            for ap_spec in spec.action_payloads:
                name_to_module[ap_spec.class_name] = module_name

        # Add request-model exports
        for root_name, rm_spec in REQUEST_MODEL_SPECS.items():
            descendants = self.meta.concrete_descendants(root_name)
            enum_names = []
            seen: set[str] = set()
            for tn in [root_name, *descendants]:
                for prop in self.meta.declared_props_for(tn):
                    short = strip_prefix(unwrap_collection(prop.get("Type", "")))
                    if short in self.meta.enum_types and short not in seen:
                        seen.add(short)
                        enum_names.append(short)
            for en in enum_names:
                name_to_module[to_const(en)] = rm_spec.module
            for d in descendants:
                name_to_module[d] = rm_spec.module
            name_to_module[rm_spec.union_name] = rm_spec.module

        seen_modules: dict[str, list[str]] = {}
        for name, module in name_to_module.items():
            seen_modules.setdefault(module, []).append(name)

        type_checking_lines: list[str] = []
        for module, names in seen_modules.items():
            if len(names) == 1:
                type_checking_lines.append(f"    from .{module} import {names[0]}")
            else:
                joined = ",\n        ".join(names)
                type_checking_lines.append(
                    f"    from .{module} import (\n        {joined},\n    )"
                )

        registry_lines: list[str] = ["_NAME_TO_MODULE: dict[str, str] = {"]
        for name, module in name_to_module.items():
            registry_lines.append(f'    "{name}": "{module}",')
        registry_lines.append("}")

        all_entries = ",\n    ".join(f'"{n}"' for n in sorted(name_to_module))

        lines: list[str] = [
            "# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.",
            "# Re-run the script to regenerate when MDE $metadata changes.",
            "from __future__ import annotations",
            "",
            "import importlib",
            "from typing import TYPE_CHECKING",
            "",
            "if TYPE_CHECKING:",
            *type_checking_lines,
            "",
            *registry_lines,
            "",
            "",
            "def __getattr__(name: str) -> object:",
            '    """Lazily import model constants on first access (PEP 562).',
            "",
            "    The resolved value is written back into the module's globals so",
            "    subsequent accesses skip this function entirely.",
            '    """',
            "    module_name = _NAME_TO_MODULE.get(name)",
            "    if module_name is None:",
            '        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")',
            "    module = importlib.import_module(f'.{module_name}', __name__)",
            "    value = getattr(module, name)",
            "    globals()[name] = value  # cache: subsequent access bypasses __getattr__",
            "    return value",
            "",
            "",
            "__all__ = [",
            f"    {all_entries},",
            "]",
            "",
        ]

        return "\n".join(lines)


def cleanup_stale_models(expected_paths: set[Path]) -> None:
    """Remove AUTO-GENERATED model files that are no longer in the expected set."""
    for path in sorted(MODELS_OUTPUT_DIR.glob("*.py")):
        if path.name == "__init__.py":
            continue
        if path in expected_paths:
            continue
        try:
            first_line = path.read_text(encoding="utf-8").split("\n", 1)[0]
        except OSError:
            continue
        if _GENERATED_HEADER in first_line:
            path.unlink()
            print(f"  🗑  removed stale {path.name}")


# ── CLI ───────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate PyArrow schema files from MDE $metadata XML."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated source to stdout instead of writing files.",
    )
    parser.add_argument(
        "--entity",
        metavar="NAME",
        help="Generate only the schema for this EntityType (e.g. 'Alert').",
    )

    fetch_group = parser.add_mutually_exclusive_group()
    fetch_group.add_argument(
        "--refresh-metadata",
        action="store_true",
        help="Force re-fetch of $metadata from the API before generating schemas.",
    )
    fetch_group.add_argument(
        "--no-fetch",
        action="store_true",
        help="Skip the staleness check and generate from existing XML as-is. "
        "Useful when credentials are unavailable locally.",
    )
    args = parser.parse_args()

    # ── Metadata freshness check ──────────────────────────────────────────────

    if args.no_fetch:
        if not XML_SOURCE.exists():
            raise FileNotFoundError(
                f"{XML_SOURCE} not found. Cannot use --no-fetch without existing XML. "
                "Run without --no-fetch to fetch it first."
            )
        print(f"  Using existing {XML_SOURCE} (--no-fetch)")
    elif args.refresh_metadata or metadata_is_stale():
        if not all(
            k in os.environ
            for k in ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET")
        ):
            raise EnvironmentError(
                "AZURE_TENANT_ID, AZURE_CLIENT_ID, and AZURE_CLIENT_SECRET must be "
                "set to fetch metadata from the MDE API.\n"
                "To generate from existing XML without credentials, use --no-fetch."
            )
        fetch_metadata()

    if not XML_SOURCE.exists():
        raise FileNotFoundError(
            f"{XML_SOURCE} not found. Run with --refresh-metadata to fetch it."
        )

    # ── Parse and generate ────────────────────────────────────────────────────

    meta = MDEMetadata(XML_SOURCE)
    gen = SchemaCodeGen(meta)
    request_model_gen = RequestModelCodeGen(meta)
    support_model_gen = SupportModelCodeGen(meta)

    available_schema_types = sorted(
        (set(meta.entity_types) - SKIP_ENTITIES) | meta.response_complex_types
    )

    if args.entity and args.entity not in available_schema_types:
        available = ", ".join(available_schema_types)
        raise ValueError(f"Unknown entity {args.entity!r}.\nAvailable: {available}")

    all_schema_types = available_schema_types
    types_to_generate = (
        sorted({args.entity, *meta.response_complex_types})
        if args.entity
        else all_schema_types
    )

    if not args.dry_run:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        MODELS_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # ── Per-entity schema files ───────────────────────────────────────────────

    expected_schema_paths: set[Path] = set()
    schema_count = 0

    for type_name in types_to_generate:
        source = gen.generate(type_name)
        out_path = OUTPUT_DIR / (camel_to_snake(type_name) + ".py")
        expected_schema_paths.add(out_path)

        if args.dry_run:
            sep = "─" * 60
            print(f"\n{sep}\n# {out_path}\n{sep}")
            print(source)
        else:
            out_path.write_text(source, encoding="utf-8")
            print(f"  ✓ {out_path}")

        schema_count += 1

    # ── Request model files (written to models/) ──────────────────────────────

    expected_model_paths: set[Path] = set()
    request_model_count = 0

    request_model_roots = [
        root_name
        for root_name in REQUEST_MODEL_SPECS
        if not args.entity
        or root_name == args.entity
        or root_name in meta.referenced_complex_types(args.entity)
    ]

    for root_name in request_model_roots:
        spec = REQUEST_MODEL_SPECS[root_name]
        source = request_model_gen.generate(root_name, spec)
        out_path = MODELS_OUTPUT_DIR / f"{spec.module}.py"
        expected_model_paths.add(out_path)

        if args.dry_run:
            sep = "─" * 60
            print(f"\n{sep}\n# {out_path}\n{sep}")
            print(source)
        else:
            out_path.write_text(source, encoding="utf-8")
            print(f"  ✓ {out_path}")

        request_model_count += 1

    # ── Support model files (written to models/) ─────────────────────────────

    support_model_count = 0

    for module_name, module_spec in SUPPORT_MODULE_SPECS.items():
        source = support_model_gen.generate(module_name, module_spec)
        out_path = MODELS_OUTPUT_DIR / f"{module_name}.py"
        expected_model_paths.add(out_path)

        if args.dry_run:
            sep = "─" * 60
            print(f"\n{sep}\n# {out_path}\n{sep}")
            print(source)
        else:
            out_path.write_text(source, encoding="utf-8")
            print(f"  ✓ {out_path}")

        support_model_count += 1

    # ── schemas/__init__.py ───────────────────────────────────────────────────

    init_source = gen.generate_init(all_schema_types)
    init_path = OUTPUT_DIR / "__init__.py"

    if args.dry_run:
        sep = "─" * 60
        print(f"\n{sep}\n# {init_path}\n{sep}")
        print(init_source)
    else:
        init_path.write_text(init_source, encoding="utf-8")
        print(f"  ✓ {init_path}")

    # ── models/__init__.py ────────────────────────────────────────────────────

    models_init_source = support_model_gen.generate_init(SUPPORT_MODULE_SPECS)
    models_init_path = MODELS_OUTPUT_DIR / "__init__.py"

    if args.dry_run:
        sep = "─" * 60
        print(f"\n{sep}\n# {models_init_path}\n{sep}")
        print(models_init_source)
    else:
        models_init_path.write_text(models_init_source, encoding="utf-8")
        print(f"  ✓ {models_init_path}")

    # ── Stale file cleanup ────────────────────────────────────────────────────
    # Only on full runs (not --entity) so we don't remove files we didn't intend
    # to touch. Skipped in dry-run mode.

    if not args.entity and not args.dry_run:
        cleanup_stale_schemas(expected_schema_paths)
        cleanup_stale_models(expected_model_paths)

    # ── Quality gate ──────────────────────────────────────────────────────────

    if not args.dry_run:
        print(
            f"\n{schema_count} schema file(s), {request_model_count} request model module(s), "
            f"{support_model_count} support model module(s) written."
        )
        run_quality()


if __name__ == "__main__":
    main()
