# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

ASSET_BROWSER_EXTENSION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("deviceId", pa.string()),
        pa.field("rbacGroupId", pa.int64(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
        pa.field("installationTime", pa.timestamp("us", tz="UTC")),
        pa.field("browserName", pa.string()),
        pa.field("extensionId", pa.string()),
        pa.field("extensionName", pa.string()),
        pa.field("extensionDescription", pa.string()),
        pa.field("extensionVersion", pa.string()),
        pa.field("extensionRisk", pa.string()),
        pa.field("extensionVendor", pa.string()),
        pa.field("isActivated", pa.bool_(), nullable=False),
    ]
)
