# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

LIST_1_OF_INDICATOR_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("capacity", pa.int32(), nullable=False),
    ]
)
