"""Emit PyArrow source exclusively from a validated canonical contract."""

from __future__ import annotations

from pathlib import Path

from ..builder import to_const
from ..models import ContractField, ItemSpec, SourceContract

_PRIMITIVE_EXPRESSIONS = {
    "Edm.String": "pa.string()",
    "Edm.Int16": "pa.int16()",
    "Edm.Int32": "pa.int32()",
    "Edm.Int64": "pa.int64()",
    "Edm.Boolean": "pa.bool_()",
    "Edm.Double": "pa.float64()",
    "Edm.Single": "pa.float32()",
    "Edm.Byte": "pa.uint8()",
    "Edm.SByte": "pa.int8()",
    "Edm.Guid": "pa.string()",
    "Edm.DateTimeOffset": 'pa.timestamp("us", tz="UTC")',
    "Edm.Duration": 'pa.duration("us")',
    "Edm.TimeOfDay": 'pa.time64("us")',
    "Edm.Binary": "pa.large_binary()",
}

_HEADER = (
    "# AUTO-GENERATED by mde-contract-gen — do not edit manually.\n"
    "# Run `just contracts-generate` to regenerate.\n"
    "from __future__ import annotations\n\n"
    "import pyarrow as pa\n\n"
    "__generated__ = True"
)


def emit_arrow(contract_path: Path, output_path: Path) -> None:
    contract = SourceContract.model_validate_json(
        contract_path.read_text(encoding="utf-8")
    )
    output_path.write_text(render_arrow(contract), encoding="utf-8")


def render_arrow(contract: SourceContract) -> str:
    parts = [_HEADER, ""]
    for name in _definition_order(contract):
        definition = contract.definitions[name]
        parts.append(
            _render_fields(
                f"{to_const(name)}_TYPE",
                "pa.StructType",
                "pa.struct",
                definition.fields,
            )
        )
        parts.append("")
    parts.append(
        _render_fields(
            f"{to_const(contract.source.entity_type)}_SCHEMA",
            "pa.Schema",
            "pa.schema",
            contract.fields,
        )
    )
    parts.append("")
    return "\n".join(parts)


def _render_fields(
    constant: str,
    annotation: str,
    constructor: str,
    fields: list[ContractField],
) -> str:
    lines = [f"{constant}: {annotation} = {constructor}(", "    ["]
    lines.extend(_field_line(field) for field in fields)
    lines.extend(["    ]", ")"])
    return "\n".join(lines)


def _field_line(field: ContractField) -> str:
    nullable = "" if field.nullable else ", nullable=False"
    return f'        pa.field("{field.name}", {_type_expr(field)}{nullable}),'


def _type_expr(field: ContractField) -> str:
    if field.items is not None:
        return f"pa.list_({_item_type_expr(field.items)})"
    if field.ref:
        return f"{to_const(field.ref)}_TYPE"
    return _primitive_expr(field.source_type, field)


def _item_type_expr(item: ItemSpec) -> str:
    if item.ref:
        return f"{to_const(item.ref)}_TYPE"
    return _primitive_expr(item.source_type or "Edm.String", item)


def _primitive_expr(source_type: str, descriptor: object) -> str:
    expression = _PRIMITIVE_EXPRESSIONS.get(source_type)
    if expression:
        return expression
    if source_type == "Edm.Decimal":
        constraints = getattr(descriptor, "constraints", None)
        precision = getattr(constraints, "precision", None)
        scale = getattr(constraints, "scale", None)
        if isinstance(precision, int) and isinstance(scale, int):
            return f"pa.decimal128({precision}, {scale})"
        raise ValueError("Edm.Decimal requires integer precision and scale")
    if getattr(descriptor, "enum_ref", None):
        return "pa.string()"
    return "pa.string()"


def _definition_order(contract: SourceContract) -> list[str]:
    ordered: list[str] = []
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(name: str) -> None:
        if name in visited:
            return
        if name in visiting:
            raise ValueError(f"Definition reference cycle at {name!r}")
        visiting.add(name)
        for field in contract.definitions[name].fields:
            refs = [field.ref]
            if field.items:
                refs.append(field.items.ref)
            for ref in refs:
                if ref:
                    visit(ref)
        visiting.remove(name)
        visited.add(name)
        ordered.append(name)

    for definition_name in contract.definitions:
        visit(definition_name)
    return ordered
