"""Emit portable Draft 2020-12 JSON Schema from canonical contracts."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator

from ..models import ContractField, ItemSpec, LogicalType, SourceContract

DRAFT_2020_12 = "https://json-schema.org/draft/2020-12/schema"


def emit_json_schema(contract_path: Path, output_path: Path) -> None:
    contract = SourceContract.model_validate_json(
        contract_path.read_text(encoding="utf-8")
    )
    schema = build_json_schema(contract)
    Draft202012Validator.check_schema(schema)
    output_path.write_text(
        json.dumps(schema, indent=2, ensure_ascii=False, allow_nan=False) + "\n",
        encoding="utf-8",
    )


def build_json_schema(contract: SourceContract) -> dict[str, Any]:
    schema: dict[str, Any] = {
        "$schema": DRAFT_2020_12,
        "$id": f"urn:{contract.name}:{contract.version}",
        "$comment": (
            "AUTO-GENERATED by mde-contract-gen; do not edit manually; generated: true"
        ),
        "title": contract.title,
        "type": "object",
        "properties": {field.name: _field_schema(field) for field in contract.fields},
    }
    if contract.description:
        schema["description"] = contract.description
    required = [field.name for field in contract.fields if field.required]
    if required:
        schema["required"] = required
    if contract.definitions:
        schema["$defs"] = {
            name: _definition_schema(definition.fields)
            for name, definition in contract.definitions.items()
        }
    return schema


def _definition_schema(fields: list[ContractField]) -> dict[str, Any]:
    schema: dict[str, Any] = {
        "type": "object",
        "properties": {field.name: _field_schema(field) for field in fields},
    }
    required = [field.name for field in fields if field.required]
    if required:
        schema["required"] = required
    return schema


def _field_schema(field: ContractField) -> dict[str, Any]:
    if field.ref:
        schema = _ref_schema(field.ref, field.nullable)
    elif field.items:
        schema = {
            "type": ["array", "null"] if field.nullable else "array",
            "items": _item_schema(field.items),
        }
    else:
        schema = _scalar_schema(
            field.logical_type,
            nullable=field.nullable,
            semantic=field.format.semantic if field.format else None,
        )
    if field.description:
        schema["description"] = field.description
    elif field.notes:
        schema["description"] = field.notes
    return schema


def _item_schema(item: ItemSpec) -> dict[str, Any]:
    if item.ref:
        return _ref_schema(item.ref, item.nullable)
    return _scalar_schema(
        item.logical_type,
        nullable=item.nullable,
        semantic=item.format.semantic if item.format else None,
    )


def _ref_schema(ref: str, nullable: bool) -> dict[str, Any]:
    target = {"$ref": f"#/$defs/{ref}"}
    if not nullable:
        return target
    return {"anyOf": [target, {"type": "null"}]}


def _scalar_schema(
    logical_type: LogicalType,
    *,
    nullable: bool,
    semantic: str | None,
) -> dict[str, Any]:
    json_type = {
        LogicalType.STRING: "string",
        LogicalType.INTEGER: "integer",
        LogicalType.NUMBER: "number",
        LogicalType.BOOLEAN: "boolean",
        LogicalType.DATETIME: "string",
    }.get(logical_type)
    if json_type is None:
        raise ValueError(f"Unsupported scalar logical type {logical_type!r}")
    schema: dict[str, Any] = {"type": [json_type, "null"] if nullable else json_type}
    if logical_type == LogicalType.DATETIME:
        schema["format"] = "date-time"
    elif semantic == "uuid":
        schema["format"] = "uuid"
    elif semantic == "time":
        schema["format"] = "time"
    elif semantic == "base64":
        schema["contentEncoding"] = "base64"
    return schema
