"""Generate runtime aggregation and legacy schema compatibility modules."""

from __future__ import annotations

from pathlib import Path
from pprint import pformat

from ..builder import to_const
from ..models import SourceContract

_HEADER = (
    "# AUTO-GENERATED by mde-contract-gen — do not edit manually.\n"
    "# Run `just contracts-generate` to regenerate.\n"
)


def emit_package_files(
    contracts: dict[str, SourceContract],
    *,
    contracts_dir: Path,
    schemas_dir: Path,
    source_models_path: Path,
) -> None:
    name_to_slug = _name_to_slug(contracts)
    (contracts_dir / "__init__.py").write_text(
        _render_contracts_init(contracts, name_to_slug), encoding="utf-8"
    )
    (contracts_dir / "_models.py").write_text(
        _render_runtime_models(source_models_path), encoding="utf-8"
    )
    schemas_dir.mkdir(parents=True, exist_ok=True)
    (schemas_dir / "__init__.py").write_text(
        _render_schemas_init(name_to_slug), encoding="utf-8"
    )
    expected_wrappers: set[Path] = set()
    for slug, contract in contracts.items():
        path = schemas_dir / f"{slug}.py"
        expected_wrappers.add(path)
        names = [f"{to_const(contract.source.entity_type)}_SCHEMA"]
        names.extend(f"{to_const(name)}_TYPE" for name in contract.definitions)
        path.write_text(_render_wrapper(slug, names), encoding="utf-8")
    for path in schemas_dir.glob("*.py"):
        if path.name == "__init__.py" or path in expected_wrappers:
            continue
        first_line = path.read_text(encoding="utf-8").splitlines()[0]
        if first_line.startswith("# AUTO-GENERATED"):
            path.unlink()


def _name_to_slug(contracts: dict[str, SourceContract]) -> dict[str, str]:
    result: dict[str, str] = {}
    for slug, contract in sorted(contracts.items()):
        result.setdefault(f"{to_const(contract.source.entity_type)}_SCHEMA", slug)
        for definition_name in contract.definitions:
            result.setdefault(f"{to_const(definition_name)}_TYPE", slug)
    return result


def _render_contracts_init(
    contracts: dict[str, SourceContract], name_to_slug: dict[str, str]
) -> str:
    index = {
        slug: {
            "name": contract.name,
            "version": contract.version,
            "schema": f"{to_const(contract.source.entity_type)}_SCHEMA",
        }
        for slug, contract in sorted(contracts.items())
    }
    mapping_lines = "\n".join(
        f'    "{name}": "{slug}",' for name, slug in name_to_slug.items()
    )
    all_lines = "\n".join(f'    "{name}",' for name in sorted(name_to_slug))
    typing_imports = _render_type_checking_imports(name_to_slug)
    return (
        _HEADER
        + "from __future__ import annotations\n\n"
        + "import importlib\n"
        + "from typing import TYPE_CHECKING\n\n"
        + "__generated__ = True\n\n"
        + "if TYPE_CHECKING:\n"
        + typing_imports
        + "\n"
        + "_NAME_TO_SLUG: dict[str, str] = {\n"
        + mapping_lines
        + "\n}\n\n"
        + "_CONTRACT_INDEX: dict[str, dict[str, str]] = "
        + pformat(index, sort_dicts=True, width=88)
        + "\n\n"
        + "def __getattr__(name: str) -> object:\n"
        + "    slug = _NAME_TO_SLUG.get(name)\n"
        + "    if slug is None:\n"
        + "        raise AttributeError("
        + 'f"module {__name__!r} has no attribute {name!r}")\n'
        + '    module = importlib.import_module(f".{slug}.schema", __name__)\n'
        + "    value = getattr(module, name)\n"
        + "    globals()[name] = value\n"
        + "    return value\n\n\n"
        + "__all__ = [\n"
        + all_lines
        + "\n]\n"
    )


def _render_type_checking_imports(name_to_slug: dict[str, str]) -> str:
    by_slug: dict[str, list[str]] = {}
    for name, slug in name_to_slug.items():
        by_slug.setdefault(slug, []).append(name)
    blocks: list[str] = []
    for slug, names in sorted(by_slug.items()):
        if len(names) == 1:
            blocks.append(f"    from .{slug}.schema import {names[0]}")
            continue
        members = "\n".join(f"        {name}," for name in sorted(names))
        blocks.append(f"    from .{slug}.schema import (\n{members}\n    )")
    return "\n".join(blocks) + "\n\n"


def _render_schemas_init(name_to_slug: dict[str, str]) -> str:
    all_lines = "\n".join(f'    "{name}",' for name in sorted(name_to_slug))
    typing_names = "\n".join(f"        {name}," for name in sorted(name_to_slug))
    return (
        _HEADER
        + "from __future__ import annotations\n\n"
        + "from typing import TYPE_CHECKING\n\n"
        + "import mde_client.contracts as _contracts\n\n"
        + "__generated__ = True\n\n\n"
        + "if TYPE_CHECKING:\n"
        + "    from mde_client.contracts import (\n"
        + typing_names
        + "\n    )\n\n\n"
        + "def __getattr__(name: str) -> object:\n"
        + "    try:\n"
        + "        value = getattr(_contracts, name)\n"
        + "    except AttributeError as exc:\n"
        + "        raise AttributeError("
        + 'f"module {__name__!r} has no attribute {name!r}") from exc\n'
        + "    globals()[name] = value\n"
        + "    return value\n\n\n"
        + "__all__ = [\n"
        + all_lines
        + "\n]\n"
    )


def _render_wrapper(slug: str, names: list[str]) -> str:
    imports = ",\n    ".join(sorted(set(names)))
    all_names = ",\n    ".join(f'"{name}"' for name in sorted(set(names)))
    return (
        _HEADER
        + "from __future__ import annotations\n\n"
        + f"from mde_client.contracts.{slug}.schema import (\n"
        + f"    {imports},\n"
        + ")\n\n"
        + "__generated__ = True\n\n"
        + "__all__ = [\n"
        + f"    {all_names},\n"
        + "]\n"
    )


def _render_runtime_models(source_path: Path) -> str:
    source = source_path.read_text(encoding="utf-8")
    source = source.replace(
        "from __future__ import annotations\n",
        "from __future__ import annotations\n\n__generated__ = True\n",
        1,
    )
    return _HEADER + source
