"""Preserve the existing EDMX-derived public request/support model surface."""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from ..builder import to_const
from ..edmx import (
    Metadata,
    OperationDefinition,
    PropertyDefinition,
    short_type_name,
    unwrap_collection,
)

_HEADER = (
    "# AUTO-GENERATED by mde-contract-gen — do not edit manually.\n"
    "# Run `just contracts-generate` to regenerate.\n"
)

_PRIMITIVES = {
    "Edm.String": "str",
    "Edm.Int16": "int",
    "Edm.Int32": "int",
    "Edm.Int64": "int",
    "Edm.Boolean": "bool",
    "Edm.Double": "float",
    "Edm.Single": "float",
    "Edm.Byte": "int",
    "Edm.SByte": "int",
    "Edm.Guid": "str",
}

_SKIP_ENUMS = {"microsoft.windowsDefenderATP.api"}


def emit_support_models(metadata: Metadata, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    generated = {
        "enums.py": _render_enums(metadata),
        "action_payloads.py": _render_action_payloads(metadata),
        "auth_params_models.py": _render_auth_models(metadata),
        "__init__.py": _render_init(metadata),
    }
    for filename, source in generated.items():
        (output_dir / filename).write_text(source, encoding="utf-8")
    for path in output_dir.glob("*.py"):
        if path.name in generated:
            continue
        first_line = path.read_text(encoding="utf-8").splitlines()[0]
        if first_line.startswith("# AUTO-GENERATED"):
            path.unlink()


def _render_enums(metadata: Metadata) -> str:
    enum_names = sorted(set(metadata.enum_types) - _SKIP_ENUMS)
    literal_lines = [
        _literal(name, metadata.enum_types[name].members) for name in enum_names
    ]
    all_lines = "\n".join(f'    "{to_const(name)}",' for name in enum_names)
    return (
        _HEADER
        + "from __future__ import annotations\n\n"
        + "from typing import Literal\n\n"
        + "__generated__ = True\n\n"
        + "\n".join(literal_lines)
        + "\n\n__all__ = [  # noqa: RUF022\n"
        + all_lines
        + "\n]\n"
    )


def _render_action_payloads(metadata: Metadata) -> str:
    operations = sorted(
        (operation for operation in metadata.operations if operation.parameters),
        key=lambda operation: (
            operation.name,
            short_type_name(operation.binding_type or ""),
        ),
    )
    name_counts = Counter(operation.name for operation in operations)
    enum_dependencies = sorted(
        {
            to_const(short_type_name(parameter.type_name))
            for operation in operations
            for parameter in operation.parameters
            if short_type_name(parameter.type_name) in metadata.enum_types
        }
    )
    import_block = ""
    if enum_dependencies:
        import_block = (
            "from mde_client.models.enums import (\n"
            + "\n".join(f"    {name}," for name in enum_dependencies)
            + "\n)\n\n"
        )
    blocks: list[str] = []
    class_names: list[str] = []
    for operation in operations:
        class_name = _payload_class_name(operation, name_counts)
        class_names.append(class_name)
        lines = [f"class {class_name}(BasePayload):"]
        for parameter in operation.parameters:
            type_expression = _action_python_type(metadata, parameter.type_name)
            if parameter.optional:
                lines.append(f"    {parameter.name}: {type_expression} | None = None")
            else:
                lines.append(f"    {parameter.name}: {type_expression}")
        blocks.append("\n".join(lines))
    all_lines = "\n".join(f'    "{name}",' for name in class_names)
    return (
        _HEADER
        + "from __future__ import annotations\n\n"
        + "from mde_client.endpoints.base import BasePayload\n"
        + (import_block if import_block else "\n")
        + "__generated__ = True\n\n\n"
        + "\n\n\n".join(blocks)
        + "\n\n\n__all__ = [\n"
        + all_lines
        + "\n]\n"
    )


def _render_auth_models(metadata: Metadata) -> str:
    root_name = "AuthParamsBase"
    root = metadata.complex_types[root_name]
    descendants = metadata.concrete_descendants(root_name)
    enum_names: list[str] = []
    for type_name in (root_name, *descendants):
        for prop in metadata.complex_types[type_name].properties:
            enum_name = short_type_name(prop.type_name)
            if enum_name in metadata.enum_types and enum_name not in enum_names:
                enum_names.append(enum_name)
    literals = "\n".join(
        _literal(name, metadata.enum_types[name].members) for name in enum_names
    )
    blocks = [
        "class _AuthParamsBase(BaseModel):\n"
        '    model_config = {"extra": "forbid"}\n\n'
        + "\n".join(_model_field(metadata, prop) for prop in root.properties)
    ]
    for descendant_name in descendants:
        descendant = metadata.complex_types[descendant_name]
        fields = "\n".join(
            _model_field(metadata, prop) for prop in descendant.properties
        )
        blocks.append(f"class {descendant_name}(_AuthParamsBase):\n{fields}")
    union = " | ".join(descendants)
    all_names = [
        *(to_const(name) for name in enum_names),
        *descendants,
        "SCANAUTHENTICATIONPARAMS",
    ]
    all_lines = "\n".join(f'    "{name}",' for name in all_names)
    return (
        _HEADER
        + "from __future__ import annotations\n\n"
        + "from typing import Annotated, Literal\n\n"
        + "from pydantic import BaseModel, Field\n\n"
        + "__generated__ = True\n\n"
        + literals
        + "\n\n\n"
        + "\n\n\n".join(blocks)
        + "\n\n\nSCANAUTHENTICATIONPARAMS = Annotated[\n"
        + f"    {union},\n"
        + '    Field(discriminator="type"),\n'
        + "]\n\n\n__all__ = [  # noqa: RUF022\n"
        + all_lines
        + "\n]\n"
    )


def _render_init(metadata: Metadata) -> str:
    name_to_module: dict[str, str] = {}
    for name in sorted(set(metadata.enum_types) - _SKIP_ENUMS):
        name_to_module[to_const(name)] = "enums"
    operations = [
        operation for operation in metadata.operations if operation.parameters
    ]
    name_counts = Counter(operation.name for operation in operations)
    for operation in sorted(
        operations,
        key=lambda item: (item.name, short_type_name(item.binding_type or "")),
    ):
        name_to_module[_payload_class_name(operation, name_counts)] = "action_payloads"
    root_name = "AuthParamsBase"
    descendants = metadata.concrete_descendants(root_name)
    for type_name in (root_name, *descendants):
        for prop in metadata.complex_types[type_name].properties:
            enum_name = short_type_name(prop.type_name)
            if enum_name in metadata.enum_types:
                name_to_module[to_const(enum_name)] = "auth_params_models"
    for descendant in descendants:
        name_to_module[descendant] = "auth_params_models"
    name_to_module["SCANAUTHENTICATIONPARAMS"] = "auth_params_models"

    mapping_lines = "\n".join(
        f'    "{name}": "{module}",' for name, module in sorted(name_to_module.items())
    )
    all_lines = "\n".join(f'    "{name}",' for name in sorted(name_to_module))
    typing_imports = _render_model_type_checking_imports(name_to_module)
    return (
        _HEADER
        + "from __future__ import annotations\n\n"
        + "import importlib\n"
        + "from typing import TYPE_CHECKING\n\n"
        + "__generated__ = True\n\n"
        + "if TYPE_CHECKING:\n"
        + typing_imports
        + "\n"
        + "_NAME_TO_MODULE: dict[str, str] = {\n"
        + mapping_lines
        + "\n}\n\n\n"
        + "def __getattr__(name: str) -> object:\n"
        + "    module_name = _NAME_TO_MODULE.get(name)\n"
        + "    if module_name is None:\n"
        + "        raise AttributeError("
        + 'f"module {__name__!r} has no attribute {name!r}")\n'
        + '    module = importlib.import_module(f".{module_name}", __name__)\n'
        + "    value = getattr(module, name)\n"
        + "    globals()[name] = value\n"
        + "    return value\n\n\n"
        + "__all__ = [  # noqa: RUF022\n"
        + all_lines
        + "\n]\n"
    )


def _render_model_type_checking_imports(name_to_module: dict[str, str]) -> str:
    by_module: dict[str, list[str]] = {}
    for name, module in name_to_module.items():
        by_module.setdefault(module, []).append(name)
    blocks: list[str] = []
    for module, names in sorted(by_module.items()):
        members = "\n".join(f"        {name}," for name in sorted(names))
        blocks.append(f"    from .{module} import (\n{members}\n    )")
    return "\n".join(blocks) + "\n\n"


def _literal(name: str, members: tuple[str, ...]) -> str:
    values = ", ".join(f'"{member}"' for member in members)
    return f"{to_const(name)} = Literal[{values}]"


def _python_type(metadata: Metadata, type_name: str) -> str:
    inner, collection = unwrap_collection(type_name)
    if collection:
        return f"list[{_python_type(metadata, inner)}]"
    if inner in _PRIMITIVES:
        return _PRIMITIVES[inner]
    short = short_type_name(inner)
    if short in metadata.enum_types:
        return to_const(short)
    if short in metadata.complex_types:
        return short
    return "str"


def _action_python_type(metadata: Metadata, type_name: str) -> str:
    inner, collection = unwrap_collection(type_name)
    if collection:
        return f"list[{_action_python_type(metadata, inner)}]"
    if inner in _PRIMITIVES:
        return _PRIMITIVES[inner]
    short = short_type_name(inner)
    if short in metadata.enum_types:
        return to_const(short)
    return "str"


def _model_field(metadata: Metadata, prop: PropertyDefinition) -> str:
    name = prop.name
    type_expression = _python_type(metadata, prop.type_name)
    if prop.nullable:
        return f"    {name}: {type_expression} | None = None"
    if prop.type_name == "Edm.Boolean":
        return f"    {name}: bool = False"
    return f"    {name}: {type_expression}"


def _payload_class_name(
    operation: OperationDefinition, name_counts: Counter[str]
) -> str:
    if name_counts[operation.name] > 1:
        binding = short_type_name(operation.binding_type or "")
        return f"{operation.name}{binding}Payload"
    return f"{operation.name}Payload"
