# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field

__generated__ = True

WINDOWS_AUTH_TYPE = Literal["None", "Ntlm", "Kerberos", "Negotiate"]
LINUX_AUTH_TYPE = Literal["Password", "PrivateKey"]
SNMP_AUTH_TYPE = Literal["CommunityString", "NoAuthNoPriv", "AuthNoPriv", "AuthPriv"]


class _AuthParamsBase(BaseModel):
    model_config = {"extra": "forbid"}

    keyVaultUri: str | None = None
    keyVaultSecretName: str | None = None


class WindowsAuthParams(_AuthParamsBase):
    type: WINDOWS_AUTH_TYPE
    username: str | None = None
    password: str | None = None
    domain: str | None = None
    isgmsaUser: bool = False
    packetPrivacy: bool = False
    packetIntegrity: bool = False


class LinuxAuthParams(_AuthParamsBase):
    type: LINUX_AUTH_TYPE
    username: str | None = None
    password: str | None = None
    privateKey: str | None = None


class SnmpAuthParams(_AuthParamsBase):
    type: SNMP_AUTH_TYPE
    communityString: str | None = None
    username: str | None = None
    authProtocol: str | None = None
    authPassword: str | None = None
    privProtocol: str | None = None
    privPassword: str | None = None


SCANAUTHENTICATIONPARAMS = Annotated[
    WindowsAuthParams | LinuxAuthParams | SnmpAuthParams,
    Field(discriminator="type"),
]


__all__ = [  # noqa: RUF022
    "WINDOWS_AUTH_TYPE",
    "LINUX_AUTH_TYPE",
    "SNMP_AUTH_TYPE",
    "WindowsAuthParams",
    "LinuxAuthParams",
    "SnmpAuthParams",
    "SCANAUTHENTICATIONPARAMS",
]
