# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

DLP_MACHINE_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string()),
        pa.field("computerDnsName", pa.string()),
        pa.field("healthStatus", pa.string(), nullable=False),
        pa.field("configStatus", pa.string(), nullable=False),
        pa.field("lastSeen", pa.timestamp("us", tz="UTC")),
        pa.field("osPlatform", pa.string()),
        pa.field("version", pa.string()),
    ]
)
