# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .investigation_models import (
        INVESTIGATION_STATE,
        KNOWN_REQUEST_SOURCE,
        InvestigationStartPayload,
    )
    from .auth_params_models import (
        WINDOWS_AUTH_TYPE,
        LINUX_AUTH_TYPE,
        SNMP_AUTH_TYPE,
        WindowsAuthParams,
        LinuxAuthParams,
        SnmpAuthParams,
        SCANAUTHENTICATIONPARAMS,
    )

_NAME_TO_MODULE: dict[str, str] = {
    "INVESTIGATION_STATE": "investigation_models",
    "KNOWN_REQUEST_SOURCE": "investigation_models",
    "InvestigationStartPayload": "investigation_models",
    "WINDOWS_AUTH_TYPE": "auth_params_models",
    "LINUX_AUTH_TYPE": "auth_params_models",
    "SNMP_AUTH_TYPE": "auth_params_models",
    "WindowsAuthParams": "auth_params_models",
    "LinuxAuthParams": "auth_params_models",
    "SnmpAuthParams": "auth_params_models",
    "SCANAUTHENTICATIONPARAMS": "auth_params_models",
}


def __getattr__(name: str) -> object:
    """Lazily import model constants on first access (PEP 562).

    The resolved value is written back into the module's globals so
    subsequent accesses skip this function entirely.
    """
    module_name = _NAME_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value  # cache: subsequent access bypasses __getattr__
    return value


__all__ = [
    "INVESTIGATION_STATE",
    "InvestigationStartPayload",
    "KNOWN_REQUEST_SOURCE",
    "LINUX_AUTH_TYPE",
    "LinuxAuthParams",
    "SCANAUTHENTICATIONPARAMS",
    "SNMP_AUTH_TYPE",
    "SnmpAuthParams",
    "WINDOWS_AUTH_TYPE",
    "WindowsAuthParams",
]
