# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
from __future__ import annotations

from typing import Literal

ALERT_CLASSIFICATION = Literal[
    "Unknown", "FalsePositive", "TruePositive", "InformationalExpectedActivity"
]
ALERT_DETERMINATION = Literal[
    "NotAvailable",
    "Apt",
    "Malware",
    "SecurityPersonnel",
    "SecurityTesting",
    "UnwantedSoftware",
    "Other",
    "MultiStagedAttack",
    "CompromisedAccount",
    "Phishing",
    "MaliciousUserActivity",
    "NotMalicious",
    "NoEnoughDataToValidate",
    "ConfirmedActivity",
    "LineOfBusinessApplication",
]
ALERT_SEVERITY = Literal["UnSpecified", "Informational", "Low", "Medium", "High"]
ALERT_STATUS = Literal[
    "Unknown", "Unspecified", "New", "InProgress", "Resolved", "Hidden"
]
AUTH_SCAN_TYPE = Literal["Network", "Windows", "Linux", "AdvancedActive"]
AUTHENTICATED_SCAN_STATUS = Literal["Failure", "Success", "PartialSuccess"]
AUTOMATION_LEVEL_ENUM = Literal[
    "NoAutomatedResponse",
    "SemiRequireApprovalForAllFolders",
    "SemiRequireApprovalForNonTempFolders",
    "SemiRequireApprovalForCoreFolders",
    "FullRemediateThreatsAutomatically",
]
CUSTOM_PLAYBOOK_ACTION_TYPES = Literal[
    "PutFile", "GetFile", "RunPowerShell", "RunScript"
]
CUSTOM_PLAYBOOK_COMMAND_STATUS = Literal[
    "Executing", "Completed", "Failed", "PendingResource", "Submitted", "Created"
]
CUSTOM_PLAYBOOK_PARAMS = Literal[
    "FileName",
    "Args",
    "Path",
    "ScriptName",
    "IsExternalSource",
    "FileUri",
    "ScriptHash",
    "ScriptSource",
]
DATA_ORIGIN_PRODUCT = Literal[
    "Unspecified", "Mdatp", "Itp", "Oatp", "Aad", "Mapg", "Dlp", "Mdi", "All"
]
DEFENDER_RUNNING_MODE = Literal[
    "Normal", "Passive", "SideBySidePassive", "NotRunning", "FailedGettingStatus"
]
DETECTION_SOURCE = Literal[
    "Unknown",
    "WindowsDefenderAtp",
    "WindowsDefenderAv",
    "WindowsDefenderSmartScreen",
    "iSight",
    "Bitdefender",
    "CustomerTI",
    "Ziften",
    "Lookout",
    "SentinelOne",
    "ThirdPartySensors",
    "OfficeATP",
    "AutomatedInvestigation",
    "ThreatExperts",
    "CustomDetection",
    "AzureATP",
    "MCAS",
    "MTP",
    "AAD",
    "MAPG",
    "Manual",
    "DLP",
    "AppGPolicy",
    "AppGDetection",
    "MDC",
    "Compliance",
    "Forms",
    "MailFlow",
    "MSTIC",
    "Unspecified",
    "Sentinel",
    "All",
    "ThirdParty",
    "DefenderForIoT",
    "DefenderForServers",
    "DefenderForStorage",
    "DefenderForDNS",
    "DefenderForDatabases",
    "DefenderForContainers",
    "DefenderForNetwork",
    "DefenderForAppService",
    "DefenderForKeyVault",
    "DefenderForResourceManager",
    "DefenderForApiManagement",
    "NRTAlerts",
    "ScheduledAlerts",
    "MicrosoftDefenderThreatIntelligenceAnalytics",
    "BuiltInML",
    "MicrosoftInsiderRiskManagement",
    "Nsn",
    "DefenderForAIServices",
    "SecurityCopilot",
]
DETERMINATION_TYPE = Literal["Unknown", "Malware", "Unwanted", "Clean", "Pua"]
DEVICE_MANAGED_BY = Literal[
    "Unknown",
    "Intune",
    "SystemCenterConfigurationManager",
    "MicrosoftDefenderForEndpoint",
]
DEVICE_MANAGED_BY_FROM_DB = Literal[
    "Unknown",
    "Intune",
    "SystemCenterConfigurationManager",
    "MicrosoftDefenderForEndpoint",
    "MicrosoftDefenderForEndpointWithError",
]
DEVICE_MANAGED_BY_STATUS = Literal["Unknown", "Success", "Error"]
DEVICE_VALUE = Literal["Normal", "Low", "High"]
ENTITY_TYPE = Literal[
    "Url",
    "User",
    "File",
    "Machine",
    "Ip",
    "Process",
    "Mailbox",
    "MailCluster",
    "MailMessage",
    "SecurityGroup",
    "RegistryKey",
    "Registry",
    "CommandLine",
    "CloudApplication",
    "OAuthApplication",
]
EVIDENCE_REMEDIATION_STATUS = Literal[
    "None",
    "Remediated",
    "Prevented",
    "Blocked",
    "NotFound",
    "Active",
    "PendingApproval",
    "Declined",
    "Unremediated",
    "Running",
]
EVIDENCE_VERDICT = Literal["Unknown", "Suspicious", "Malicious", "Clean"]
EXCLUSION_REASON = Literal[
    "Other",
    "InactiveDevice",
    "DuplicateDevice",
    "DeviceDoesNotExist",
    "DeviceOutOfScope",
]
EXPOSURE_LEVEL = Literal["None", "Low", "Medium", "High"]
FULL_ACTION_TYPE = Literal[
    "Unknown",
    "FullIsolation",
    "SelectiveIsolation",
    "RunAntiVirusScan",
    "CollectInvestigationPackage",
    "StopAndQuarantineFile",
    "RestrictCodeExecution",
    "InitiateInvestigation",
    "OffBoard",
    "LiveResponse",
    "Troubleshoot",
    "LogsCollection",
    "UnManagedDeviceIsolation",
    "TokenRefresh",
    "RegenerateId",
    "EnableActiveDirectoryUser",
    "DisableActiveDirectoryUser",
    "ResetPasswordActiveDirectoryUser",
    "ImmuneActiveDirectoryCustomPlaybook",
    "Unisolation",
    "UnrestrictCodeExecution",
    "UnManagedDeviceUnisolation",
    "LiveResponsePortal",
]
IOA_CATEGORY = Literal[
    "None",
    "SuspiciousActivity",
    "Malware",
    "CredentialTheft",
    "Exploit",
    "WebExploit",
    "DocumentExploit",
    "PrivilegeEscalation",
    "Persistence",
    "RemoteAccessTool",
    "CommandAndControl",
    "SuspiciousNetworkTraffic",
    "Ransomware",
    "MalwareDownload",
    "Reconnaissance",
    "WebFingerprinting",
    "Weaponization",
    "Delivery",
    "SocialEngineering",
    "CredentialStealing",
    "UnwantedSoftware",
    "Installation",
    "Backdoor",
    "Trojan",
    "PWS",
    "TrojanDownloader",
    "LateralMovement",
    "ExplorationEnumeration",
    "NetworkPropagation",
    "Exfiltration",
    "Impact",
    "InitialAccess",
    "Execution",
    "NotApplicable",
    "Collection",
    "CredentialAccess",
    "DefenseEvasion",
    "Discovery",
    "General",
]
INCIDENT_STATUS = Literal["Active", "Resolved", "InProgress", "Redirected"]
INTERFACE_TYPE = Literal[
    "Unknown",
    "Other",
    "Ethernet",
    "TokenRing",
    "PPP",
    "SoftwareLoopback",
    "ATM",
    "IEEE80211",
    "Tunnel",
    "IEEE1394",
]
INVESTIGATION_STATE = Literal[
    "Unknown",
    "Terminated",
    "SuccessfullyRemediated",
    "Benign",
    "Failed",
    "PartiallyRemediated",
    "Running",
    "PendingApproval",
    "PendingResource",
    "Disabled",
    "Queued",
    "InnerFailure",
    "PreexistingAlert",
    "UnsupportedOs",
    "UnsupportedAlertType",
    "SuppressedAlert",
    "PartiallyInvestigated",
    "TerminatedByUser",
    "TerminatedBySystem",
]
IP_INTERFACE_OPERATIONAL_STATUS = Literal[
    "Up", "Down", "Testing", "Unknown", "Dormant", "Present", "LowerLayerDown"
]
ISOLATION_TYPE = Literal["Full", "Selective", "UnManagedDevice"]
KNOWN_REQUEST_SOURCE = Literal[
    "Unspecified",
    "PublicApi",
    "Portal",
    "MCAS",
    "TVM",
    "CustomDetection",
    "BulkAction",
    "ISG",
    "NDR",
    "EndpointConfigManagement",
    "IncidentTasks",
    "MDI",
    "ActiveScan",
]
LINUX_AUTH_TYPE = Literal["Password", "PrivateKey"]
MACHINE_CONFIGURATION_STATUS = Literal[
    "Valid", "UnsupportedOs", "InactiveAV", "NotificationsDisabled", "MissingUpdate"
]
MACHINE_HEALTH_STATUS = Literal[
    "Active",
    "Inactive",
    "ImpairedCommunication",
    "NoSensorData",
    "NoSensorDataImpairedCommunication",
    "Unknown",
]
ONBOARDING_STATUS = Literal[
    "InsufficientInfo", "Onboarded", "CanBeOnboarded", "Unsupported"
]
OPERATOR_TYPE = Literal["StartsWith", "EndsWith", "Equals", "Contains", "In"]
PUBLIC_RECOMMENDATION_EXCEPTION_STATUS = Literal[
    "Active", "Exception", "PartialException"
]
PUBLIC_VULNERABILITY_EXCEPTION_STATUS_DTO = Literal[
    "RemediationRequired", "NoActionRequired", "UnderException", "PartialException"
]
RISK_SCORE = Literal["None", "Informational", "Low", "Medium", "High"]
SCAN_STATUS = Literal["Success", "Fail"]
SCAN_TYPE = Literal["Quick", "Full"]
SERVICE_SOURCE = Literal[
    "Unspecified",
    "MicrosoftDefenderForEndpoint",
    "MicrosoftDefenderForIdentity",
    "MicrosoftCloudAppSecurity",
    "MicrosoftDefenderForOffice365",
    "Microsoft365Defender",
    "AADIdentityProtection",
    "MicrosoftApplicationProtection",
    "MicrosoftEndPointDlp",
    "UnknownFutureValue",
    "MicrosoftDefenderForCloud",
    "MicrosoftSentinel",
    "MicrosoftInsiderRiskManagement",
]
SNMP_AUTH_TYPE = Literal["CommunityString", "NoAuthNoPriv", "AuthNoPriv", "AuthPriv"]
TAG_ACTION = Literal["Add", "Remove"]
TARGET_TYPE = Literal["Ip", "Hostname", "Combined"]
TASK_CATEGORY_DTO = Literal["Software", "SecurityConfiguration"]
TASK_COMPLETION_METHOD = Literal["Manual", "Automatic"]
TASK_PRIORITY_DTO = Literal["None", "Low", "Medium", "High"]
TASK_PRODUCTIVITY_IMPACT_TYPE_DTO = Literal["AllExposedAssets", "NonImpactedAssets"]
TASK_STATE_VALUE_TYPE_DTO = Literal["Active", "Completed"]
TASK_TYPE_DTO = Literal[
    "Update",
    "Uninstall",
    "ConfigurationChange",
    "AttentionRequired",
    "Upgrade",
    "FirmwareUpdate",
]
WINDOWS_AUTH_TYPE = Literal["None", "Ntlm", "Kerberos", "Negotiate"]
ACTION_STATUS = Literal[
    "Pending", "Cancelled", "TimeOut", "Failed", "InProgress", "Succeeded"
]
ACTION_TYPE = Literal[
    "Unknown",
    "RequestSample",
    "Block",
    "RunAntiVirusScan",
    "Offboard",
    "RegenerateId",
    "CollectInvestigationPackage",
    "Isolate",
    "Unisolate",
    "StopAndQuarantineFile",
    "RestrictCodeExecution",
    "UnrestrictCodeExecution",
    "LiveResponse",
    "Troubleshoot",
    "LogsCollection",
    "TokenRefresh",
    "EndpointConfigManagementCheckin",
    "EnableActiveDirectoryUser",
    "DisableActiveDirectoryUser",
    "ResetPasswordActiveDirectoryUser",
    "ImmuneActiveDirectoryCustomPlaybook",
]
FILE_IDENTIFIER_TYPE = Literal["Sha1", "Sha256", "Md5"]
SEVERITY = Literal["Informational", "Low", "Medium", "High"]
TI_INDICATOR_ACTION = Literal[
    "Allowed", "Alert", "AlertAndBlock", "Warn", "Block", "Audit", "BlockAndRemediate"
]
TI_INDICATOR_TYPE = Literal[
    "FileSha1",
    "FileSha256",
    "FileMd5",
    "IpAddress",
    "DomainName",
    "Url",
    "CertificateThumbprint",
    "ProcessMemorySimilarityHash",
    "WebCategory",
]
VM_CLOUD_PROVIDER = Literal["Unknown", "Azure"]

__all__ = [
    "ALERT_CLASSIFICATION",
    "ALERT_DETERMINATION",
    "ALERT_SEVERITY",
    "ALERT_STATUS",
    "AUTH_SCAN_TYPE",
    "AUTHENTICATED_SCAN_STATUS",
    "AUTOMATION_LEVEL_ENUM",
    "CUSTOM_PLAYBOOK_ACTION_TYPES",
    "CUSTOM_PLAYBOOK_COMMAND_STATUS",
    "CUSTOM_PLAYBOOK_PARAMS",
    "DATA_ORIGIN_PRODUCT",
    "DEFENDER_RUNNING_MODE",
    "DETECTION_SOURCE",
    "DETERMINATION_TYPE",
    "DEVICE_MANAGED_BY",
    "DEVICE_MANAGED_BY_FROM_DB",
    "DEVICE_MANAGED_BY_STATUS",
    "DEVICE_VALUE",
    "ENTITY_TYPE",
    "EVIDENCE_REMEDIATION_STATUS",
    "EVIDENCE_VERDICT",
    "EXCLUSION_REASON",
    "EXPOSURE_LEVEL",
    "FULL_ACTION_TYPE",
    "IOA_CATEGORY",
    "INCIDENT_STATUS",
    "INTERFACE_TYPE",
    "INVESTIGATION_STATE",
    "IP_INTERFACE_OPERATIONAL_STATUS",
    "ISOLATION_TYPE",
    "KNOWN_REQUEST_SOURCE",
    "LINUX_AUTH_TYPE",
    "MACHINE_CONFIGURATION_STATUS",
    "MACHINE_HEALTH_STATUS",
    "ONBOARDING_STATUS",
    "OPERATOR_TYPE",
    "PUBLIC_RECOMMENDATION_EXCEPTION_STATUS",
    "PUBLIC_VULNERABILITY_EXCEPTION_STATUS_DTO",
    "RISK_SCORE",
    "SCAN_STATUS",
    "SCAN_TYPE",
    "SERVICE_SOURCE",
    "SNMP_AUTH_TYPE",
    "TAG_ACTION",
    "TARGET_TYPE",
    "TASK_CATEGORY_DTO",
    "TASK_COMPLETION_METHOD",
    "TASK_PRIORITY_DTO",
    "TASK_PRODUCTIVITY_IMPACT_TYPE_DTO",
    "TASK_STATE_VALUE_TYPE_DTO",
    "TASK_TYPE_DTO",
    "WINDOWS_AUTH_TYPE",
    "ACTION_STATUS",
    "ACTION_TYPE",
    "FILE_IDENTIFIER_TYPE",
    "SEVERITY",
    "TI_INDICATOR_ACTION",
    "TI_INDICATOR_TYPE",
    "VM_CLOUD_PROVIDER",
]
