# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
from __future__ import annotations

from typing import Literal

from mde_client.endpoints.base import BasePayload

INVESTIGATION_STATE = Literal[
    "Unknown",
    "Terminated",
    "SuccessfullyRemediated",
    "Benign",
    "Failed",
    "PartiallyRemediated",
    "Running",
    "PendingApproval",
    "PendingResource",
    "Disabled",
    "Queued",
    "InnerFailure",
    "PreexistingAlert",
    "UnsupportedOs",
    "UnsupportedAlertType",
    "SuppressedAlert",
    "PartiallyInvestigated",
    "TerminatedByUser",
    "TerminatedBySystem",
]
KNOWN_REQUEST_SOURCE = Literal[
    "Unspecified",
    "PublicApi",
    "Portal",
    "MCAS",
    "TVM",
    "CustomDetection",
    "BulkAction",
    "ISG",
    "NDR",
    "EndpointConfigManagement",
    "IncidentTasks",
    "MDI",
    "ActiveScan",
]


class InvestigationStartPayload(BasePayload):
    Comment: str
    ExternalId: str | None = None
    RequestSource: KNOWN_REQUEST_SOURCE | None = None
    Title: str | None = None


__all__ = [
    "INVESTIGATION_STATE",
    "KNOWN_REQUEST_SOURCE",
    "InvestigationStartPayload",
]
