# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.action_availability_status.schema import (
    ACTION_AVAILABILITY_STATUS_SCHEMA,
)

__generated__ = True

__all__ = [
    "ACTION_AVAILABILITY_STATUS_SCHEMA",
]
