# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.alert.schema import (
    ALERT_COMMENT_TYPE,
    ALERT_EVIDENCE_TYPE,
    ALERT_RELATED_USER_TYPE,
    ALERT_SCHEMA,
    DOMAIN_TYPE,
    LOGGED_ON_USER_TYPE,
)

__generated__ = True

__all__ = [
    "ALERT_COMMENT_TYPE",
    "ALERT_EVIDENCE_TYPE",
    "ALERT_RELATED_USER_TYPE",
    "ALERT_SCHEMA",
    "DOMAIN_TYPE",
    "LOGGED_ON_USER_TYPE",
]
