# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.asset_browser_extension.schema import (
    ASSET_BROWSER_EXTENSION_SCHEMA,
)

__generated__ = True

__all__ = [
    "ASSET_BROWSER_EXTENSION_SCHEMA",
]
