# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.asset_hardware_firmware.schema import (
    ASSET_HARDWARE_FIRMWARE_SCHEMA,
)

__generated__ = True

__all__ = [
    "ASSET_HARDWARE_FIRMWARE_SCHEMA",
]
