# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.asset_configuration.schema import (
    ASSET_CONFIGURATION_SCHEMA,
)

__generated__ = True

__all__ = [
    "ASSET_CONFIGURATION_SCHEMA",
]
