# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

ASSET_BROWSER_EXTENSION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("deviceId", pa.string()),
        pa.field("rbacGroupId", pa.int64(), nullable=False),
        pa.field("rbacGroupName", pa.string()),
        pa.field("installationTime", pa.timestamp("us", tz="UTC")),
        pa.field("browserName", pa.string()),
        pa.field("extensionId", pa.string()),
        pa.field("extensionName", pa.string()),
        pa.field("extensionDescription", pa.string()),
        pa.field("extensionVersion", pa.string()),
        pa.field("extensionRisk", pa.string()),
        pa.field("extensionVendor", pa.string()),
        pa.field("isActivated", pa.bool_(), nullable=False),
    ]
)
