# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

SCANNED_TARGET_RESULT_CONTRACT_TYPE: pa.StructType = pa.struct(
    [
        pa.field("scanDuration", pa.time64("us"), nullable=False),
        pa.field("ip", pa.string()),
        pa.field("hostname", pa.string()),
        pa.field("scannedDeviceDescription", pa.string()),
        pa.field("errorMessage", pa.string()),
        pa.field("scanStatus", pa.string()),
    ]
)

AUTH_SCAN_HISTORY_CONTRACT_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("orgId", pa.string()),
        pa.field("scanDefinitionId", pa.string()),
        pa.field("sessionId", pa.string()),
        pa.field("scannerId", pa.string()),
        pa.field("numberOfSuccessfullyScannedTargets", pa.int32(), nullable=False),
        pa.field("numberOfTargets", pa.int32(), nullable=False),
        pa.field("scanStatus", pa.string()),
        pa.field("generalErrorMessage", pa.string()),
        pa.field("scannedTargets", pa.list_(SCANNED_TARGET_RESULT_CONTRACT_TYPE)),
    ]
)
