# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.auth_scan_history_contract.schema import (
    AUTH_SCAN_HISTORY_CONTRACT_SCHEMA,
    SCANNED_TARGET_RESULT_CONTRACT_TYPE,
)

__generated__ = True

__all__ = [
    "AUTH_SCAN_HISTORY_CONTRACT_SCHEMA",
    "SCANNED_TARGET_RESULT_CONTRACT_TYPE",
]
