# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.baseline_profile.schema import (
    BASELINE_PROFILE_SCHEMA,
)

__generated__ = True

__all__ = [
    "BASELINE_PROFILE_SCHEMA",
]
