# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

BASELINE_CONFIGURATION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("uniqueId", pa.string()),
        pa.field("benchmarkName", pa.string()),
        pa.field("benchmarkVersion", pa.string()),
        pa.field("name", pa.string()),
        pa.field("description", pa.string()),
        pa.field("category", pa.string()),
        pa.field("complianceLevels", pa.list_(pa.string())),
        pa.field("cce", pa.string()),
        pa.field("rationale", pa.string()),
        pa.field("remediation", pa.string()),
        pa.field("recommendedValue", pa.list_(pa.string())),
        pa.field("source", pa.list_(pa.string())),
        pa.field("isCustom", pa.bool_()),
        pa.field("assessmentMethod", pa.string()),
    ]
)
