# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

BASELINE_CONFIGURATION_DTO_TYPE: pa.StructType = pa.struct(
    [
        pa.field("id", pa.string()),
        pa.field("title", pa.string()),
    ]
)

BASELINE_EXCEPTION_DEVICE_DTO_TYPE: pa.StructType = pa.struct(
    [
        pa.field("id", pa.string()),
        pa.field("name", pa.string()),
        pa.field("rbacGroupId", pa.int32(), nullable=False),
    ]
)

USER_DTO_TYPE: pa.StructType = pa.struct(
    [
        pa.field("id", pa.string()),
        pa.field("email", pa.string()),
    ]
)

BASELINE_EXCEPTION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("approvedBy", pa.string()),
        pa.field("justification", pa.string()),
        pa.field("dueDate", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("description", pa.string()),
        pa.field("status", pa.string()),
        pa.field("isActive", pa.bool_(), nullable=False),
        pa.field("softwareName", pa.string()),
        pa.field("softwareVersion", pa.string()),
        pa.field("benchmarkName", pa.string()),
        pa.field("benchmarkVersion", pa.string()),
        pa.field("complianceLevel", pa.string()),
        pa.field("configurations", pa.list_(BASELINE_CONFIGURATION_DTO_TYPE)),
        pa.field("devices", pa.list_(BASELINE_EXCEPTION_DEVICE_DTO_TYPE)),
        pa.field("lastModifiedOn", pa.timestamp("us", tz="UTC")),
        pa.field("lastModifiedBy", USER_DTO_TYPE),
        pa.field("title", pa.string()),
        pa.field("createdOn", pa.timestamp("us", tz="UTC")),
        pa.field("requester", USER_DTO_TYPE),
    ]
)
