# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.browser_extensions.schema import (
    BROWSER_EXTENSIONS_SCHEMA,
)

__generated__ = True

__all__ = [
    "BROWSER_EXTENSIONS_SCHEMA",
]
