# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

BROWSER_EXTENSIONS_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("key", pa.string(), nullable=False),
        pa.field("permissionName", pa.string()),
        pa.field("description", pa.string()),
    ]
)
