# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.configuration_score.schema import (
    CONFIGURATION_SCORE_SCHEMA,
)

__generated__ = True

__all__ = [
    "CONFIGURATION_SCORE_SCHEMA",
]
