# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.data_export_settings.schema import (
    DATA_EXPORT_SETTINGS_LOG_DEFINITION_TYPE,
    DATA_EXPORT_SETTINGS_SCHEMA,
    EVENT_HUB_PROPERTIES_TYPE,
    STORAGE_ACCOUNT_PROPERTIES_TYPE,
    WORKSPACE_PROPERTIES_TYPE,
)

__generated__ = True

__all__ = [
    "DATA_EXPORT_SETTINGS_LOG_DEFINITION_TYPE",
    "DATA_EXPORT_SETTINGS_SCHEMA",
    "EVENT_HUB_PROPERTIES_TYPE",
    "STORAGE_ACCOUNT_PROPERTIES_TYPE",
    "WORKSPACE_PROPERTIES_TYPE",
]
