# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.device_av_info.schema import (
    DEVICE_AV_INFO_SCHEMA,
)

__generated__ = True

__all__ = [
    "DEVICE_AV_INFO_SCHEMA",
]
