# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.device_group.schema import (
    AAD_USERS_GROUP_TYPE,
    DEVICE_GROUP_LIST_PROPERTY_CONDITION_TYPE,
    DEVICE_GROUP_PROPERTY_CONDITION_TYPE,
    DEVICE_GROUP_RULES_TYPE,
    DEVICE_GROUP_SCHEMA,
)

__generated__ = True

__all__ = [
    "AAD_USERS_GROUP_TYPE",
    "DEVICE_GROUP_LIST_PROPERTY_CONDITION_TYPE",
    "DEVICE_GROUP_PROPERTY_CONDITION_TYPE",
    "DEVICE_GROUP_RULES_TYPE",
    "DEVICE_GROUP_SCHEMA",
]
