# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.device_authenticated_scan_agent.schema import (
    DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA,
)

__generated__ = True

__all__ = [
    "DEVICE_AUTHENTICATED_SCAN_AGENT_SCHEMA",
]
