# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.device_authenticated_scan_definition.schema import (
    ADVANCED_ACTIVE_CONFIGURATION_TYPE,
    AGENT_CONTRACT_TYPE,
    AUTH_PARAMS_BASE_TYPE,
    DEVICE_AUTHENTICATED_SCAN_DEFINITION_SCHEMA,
    SCAN_STATE_TYPE,
)

__generated__ = True

__all__ = [
    "ADVANCED_ACTIVE_CONFIGURATION_TYPE",
    "AGENT_CONTRACT_TYPE",
    "AUTH_PARAMS_BASE_TYPE",
    "DEVICE_AUTHENTICATED_SCAN_DEFINITION_SCHEMA",
    "SCAN_STATE_TYPE",
]
