# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.dlp_machine.schema import (
    DLP_MACHINE_SCHEMA,
)

__generated__ = True

__all__ = [
    "DLP_MACHINE_SCHEMA",
]
