# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.file.schema import (
    FILE_SCHEMA,
)

__generated__ = True

__all__ = [
    "FILE_SCHEMA",
]
