# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.in_org_file_stats.schema import (
    IN_ORG_FILE_STATS_SCHEMA,
)

__generated__ = True

__all__ = [
    "IN_ORG_FILE_STATS_SCHEMA",
]
