# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.indicator.schema import (
    CERTIFICATE_INDICATOR_INFORMATION_TYPE,
    INDICATOR_SCHEMA,
)

__generated__ = True

__all__ = [
    "CERTIFICATE_INDICATOR_INFORMATION_TYPE",
    "INDICATOR_SCHEMA",
]
