# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.library_files.schema import (
    LIBRARY_FILES_SCHEMA,
)

__generated__ = True

__all__ = [
    "LIBRARY_FILES_SCHEMA",
]
