# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.list_1_of_indicator.schema import (
    LIST_1_OF_INDICATOR_SCHEMA,
)

__generated__ = True

__all__ = [
    "LIST_1_OF_INDICATOR_SCHEMA",
]
