# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.machine_action.schema import (
    CUSTOM_PLAYBOOK_COMMAND_RESULT_TYPE,
    CUSTOM_PLAYBOOK_COMMAND_TYPE,
    CUSTOM_PLAYBOOK_PARAMETER_TYPE,
    MACHINE_ACTION_SCHEMA,
    RELATED_FILE_INFO_TYPE,
    TROUBLESHOOT_INFO_TYPE,
)

__generated__ = True

__all__ = [
    "CUSTOM_PLAYBOOK_COMMAND_RESULT_TYPE",
    "CUSTOM_PLAYBOOK_COMMAND_TYPE",
    "CUSTOM_PLAYBOOK_PARAMETER_TYPE",
    "MACHINE_ACTION_SCHEMA",
    "RELATED_FILE_INFO_TYPE",
    "TROUBLESHOOT_INFO_TYPE",
]
