# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.machine.schema import (
    MACHINE_IP_ADDRESS_TYPE,
    MACHINE_SCHEMA,
    VM_METADATA_TYPE,
)

__generated__ = True

__all__ = [
    "MACHINE_IP_ADDRESS_TYPE",
    "MACHINE_SCHEMA",
    "VM_METADATA_TYPE",
]
