# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

PUBLIC_PRODUCT_DTO_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("name", pa.string()),
        pa.field("vendor", pa.string()),
        pa.field("weaknesses", pa.int64(), nullable=False),
        pa.field("publicExploit", pa.bool_(), nullable=False),
        pa.field("activeAlert", pa.bool_(), nullable=False),
        pa.field("exposedMachines", pa.int64(), nullable=False),
        pa.field("installedMachines", pa.int64(), nullable=False),
        pa.field("impactScore", pa.float32(), nullable=False),
        pa.field("isNormalized", pa.bool_(), nullable=False),
        pa.field("category", pa.string()),
    ]
)
