# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

PUBLIC_DISTRIBUTION_DTO_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("version", pa.string()),
        pa.field("installations", pa.int64(), nullable=False),
        pa.field("vulnerabilities", pa.int64(), nullable=False),
    ]
)
