# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

RECOMMENDATION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("productName", pa.string()),
        pa.field("recommendationName", pa.string()),
        pa.field("weaknesses", pa.int64(), nullable=False),
        pa.field("vendor", pa.string()),
        pa.field("recommendedVersion", pa.string()),
        pa.field("recommendedVendor", pa.string()),
        pa.field("recommendedProgram", pa.string()),
        pa.field("recommendationCategory", pa.string()),
        pa.field("subCategory", pa.string()),
        pa.field("severityScore", pa.float64(), nullable=False),
        pa.field("publicExploit", pa.bool_(), nullable=False),
        pa.field("activeAlert", pa.bool_(), nullable=False),
        pa.field("associatedThreats", pa.list_(pa.string())),
        pa.field("remediationType", pa.string()),
        pa.field("status", pa.string(), nullable=False),
        pa.field("configScoreImpact", pa.float64(), nullable=False),
        pa.field("exposureImpact", pa.float64(), nullable=False),
        pa.field("totalMachineCount", pa.int64(), nullable=False),
        pa.field("exposedMachinesCount", pa.int64(), nullable=False),
        pa.field("nonProductivityImpactedAssets", pa.int64(), nullable=False),
        pa.field("relatedComponent", pa.string()),
        pa.field("hasUnpatchableCve", pa.bool_(), nullable=False),
        pa.field("tags", pa.list_(pa.string())),
        pa.field("exposedCriticalDevices", pa.int64(), nullable=False),
    ]
)
