# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.remediation_task.schema import (
    REMEDIATION_TASK_SCHEMA,
)

__generated__ = True

__all__ = [
    "REMEDIATION_TASK_SCHEMA",
]
