# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

REMEDIATION_TASK_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("title", pa.string()),
        pa.field("createdOn", pa.timestamp("us", tz="UTC")),
        pa.field("requesterId", pa.string()),
        pa.field("requesterEmail", pa.string()),
        pa.field("status", pa.string()),
        pa.field("statusLastModifiedOn", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("description", pa.string()),
        pa.field("relatedComponent", pa.string()),
        pa.field("targetDevices", pa.int32()),
        pa.field("rbacGroupNames", pa.list_(pa.string())),
        pa.field("fixedDevices", pa.int32()),
        pa.field("requesterNotes", pa.string()),
        pa.field("dueOn", pa.timestamp("us", tz="UTC")),
        pa.field("category", pa.string()),
        pa.field("productivityImpactRemediationType", pa.string()),
        pa.field("priority", pa.string()),
        pa.field("completionMethod", pa.string()),
        pa.field("completerId", pa.string()),
        pa.field("completerEmail", pa.string()),
        pa.field("scid", pa.string()),
        pa.field("type", pa.string()),
        pa.field("productId", pa.string()),
        pa.field("vendorId", pa.string()),
        pa.field("nameId", pa.string()),
        pa.field("recommendedVersion", pa.string()),
        pa.field("recommendedVendor", pa.string()),
        pa.field("recommendedProgram", pa.string()),
        pa.field("recommendationReference", pa.string()),
    ]
)
