# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

from mde_client.contracts.software.schema import (
    PUBLIC_DISTRIBUTION_DTO_TYPE,
    SOFTWARE_SCHEMA,
)

__generated__ = True

__all__ = [
    "PUBLIC_DISTRIBUTION_DTO_TYPE",
    "SOFTWARE_SCHEMA",
]
