# AUTO-GENERATED by scripts/mde_contract.py — do not edit manually.
# Re-run the script to regenerate when MDE $metadata changes.
import pyarrow as pa

USER_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("accountName", pa.string()),
        pa.field("accountDomain", pa.string()),
        pa.field("accountSid", pa.string()),
        pa.field("firstSeen", pa.timestamp("us", tz="UTC")),
        pa.field("lastSeen", pa.timestamp("us", tz="UTC")),
        pa.field("mostPrevalentMachineId", pa.string()),
        pa.field("leastPrevalentMachineId", pa.string()),
        pa.field("logonTypes", pa.string()),
        pa.field("logOnMachinesCount", pa.int64()),
        pa.field("isDomainAdmin", pa.bool_()),
        pa.field("isOnlyNetworkUser", pa.bool_()),
    ]
)
