# AUTO-GENERATED by mde-contract-gen — do not edit manually.
# Run `just contracts-generate` to regenerate.
from __future__ import annotations

import pyarrow as pa

__generated__ = True

BROWSER_EXTENSIONS_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("key", pa.string(), nullable=False),
        pa.field("permissionName", pa.string()),
        pa.field("description", pa.string()),
    ]
)
